
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                 0
#define PARTNER_STEVEN               1
#define PARTNER_BRENDAN_SNIVY        2
#define PARTNER_BRENDAN_SCORBUNNY    3
#define PARTNER_BRENDAN_SQUIRTLE     4
#define PARTNER_MAY_SNIVY            5
#define PARTNER_MAY_SCORBUNNY        6
#define PARTNER_MAY_SQUIRTLE         7
#define PARTNER_BRENDAN_SNIVY_PW     8
#define PARTNER_BRENDAN_SCORBUNNY_PW 9
#define PARTNER_BRENDAN_SQUIRTLE_PW  10
#define PARTNER_MAY_SNIVY_PW         11
#define PARTNER_MAY_SCORBUNNY_PW     12
#define PARTNER_MAY_SQUIRTLE_PW      13

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
