# 1 "data/maps/OldaleTown_House1/scripts.pory"

# 2 "data/maps/OldaleTown_House1/scripts.pory"
.set LOCALID_GROWLITHE, 2
# 3 "data/maps/OldaleTown_House1/scripts.pory"

# 4 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_MapScripts::
# 5 "data/maps/OldaleTown_House1/scripts.pory"
	.byte 0
# 6 "data/maps/OldaleTown_House1/scripts.pory"

# 7 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_EventScript_Woman::
# 8 "data/maps/OldaleTown_House1/scripts.pory"
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
# 9 "data/maps/OldaleTown_House1/scripts.pory"
	end
# 10 "data/maps/OldaleTown_House1/scripts.pory"

# 11 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
# 12 "data/maps/OldaleTown_House1/scripts.pory"
	.string "When a POKéMON battle starts, the one\n"
# 13 "data/maps/OldaleTown_House1/scripts.pory"
	.string "at the left of the list goes out first.\p"
# 14 "data/maps/OldaleTown_House1/scripts.pory"
	.string "So, when you get more POKéMON in your\n"
# 15 "data/maps/OldaleTown_House1/scripts.pory"
	.string "party, try switching around the order\l"
# 16 "data/maps/OldaleTown_House1/scripts.pory"
	.string "of your POKéMON.\p"
# 17 "data/maps/OldaleTown_House1/scripts.pory"
	.string "It could give you an advantage.$"
