# 1 "data/scripts/pkmn_center_nurse.pory"

# 2 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 3 "data/scripts/pkmn_center_nurse.pory"
OldaleSecondaryMart::
# 4 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_AMULET_COIN
# 5 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SMOKE_BALL
# 6 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 7 "data/scripts/pkmn_center_nurse.pory"
	release
# 8 "data/scripts/pkmn_center_nurse.pory"
	end
# 9 "data/scripts/pkmn_center_nurse.pory"

# 10 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 11 "data/scripts/pkmn_center_nurse.pory"
PetalburgSecondaryMart::
# 12 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_QUICK_CLAW
# 13 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_METRONOME
# 14 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_FLOAT_STONE
# 15 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_BINDING_BAND
# 16 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_GRIP_CLAW
# 17 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 18 "data/scripts/pkmn_center_nurse.pory"
	release
# 19 "data/scripts/pkmn_center_nurse.pory"
	end
# 20 "data/scripts/pkmn_center_nurse.pory"

# 21 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 22 "data/scripts/pkmn_center_nurse.pory"
RustboroSecondaryMart::
# 23 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_RAZOR_CLAW
# 24 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_RAZOR_FANG
# 25 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_KINGS_ROCK
# 26 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_BIG_ROOT
# 27 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SCOPE_LENS
# 28 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 29 "data/scripts/pkmn_center_nurse.pory"
	release
# 30 "data/scripts/pkmn_center_nurse.pory"
	end
# 31 "data/scripts/pkmn_center_nurse.pory"

# 32 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 33 "data/scripts/pkmn_center_nurse.pory"
SlateportSecondaryMart::
# 34 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_MUSCLE_BAND
# 35 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_WISE_GLASSES
# 36 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_PUNCHING_GLOVE
# 37 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_UTILITY_UMBRELLA
# 38 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_ABILITY_SHIELD
# 39 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_COVERT_CLOAK
# 40 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_HEAVY_DUTY_BOOTS
# 41 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SAFETY_GOGGLES
# 42 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 43 "data/scripts/pkmn_center_nurse.pory"
	release
# 44 "data/scripts/pkmn_center_nurse.pory"
	end
# 45 "data/scripts/pkmn_center_nurse.pory"

# 46 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 47 "data/scripts/pkmn_center_nurse.pory"
MauvilleSecondaryMart::
# 48 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_BLACK_GLASSES
# 49 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_CHARCOAL
# 50 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_DRAGON_FANG
# 51 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_FAIRY_FEATHER
# 52 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_MAGNET
# 53 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_MIRACLE_SEED
# 54 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_MYSTIC_WATER
# 55 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NEVER_MELT_ICE
# 56 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_TWISTED_SPOON
# 57 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 58 "data/scripts/pkmn_center_nurse.pory"
	release
# 59 "data/scripts/pkmn_center_nurse.pory"
	end
# 60 "data/scripts/pkmn_center_nurse.pory"

# 61 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 62 "data/scripts/pkmn_center_nurse.pory"
VerdanturfSecondaryMart::
# 63 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_GRASSY_SEED
# 64 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_ELECTRIC_SEED
# 65 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_MISTY_SEED
# 66 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_PSYCHIC_SEED
# 67 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_MENTAL_HERB
# 68 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_MIRROR_HERB
# 69 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 70 "data/scripts/pkmn_center_nurse.pory"
	release
# 71 "data/scripts/pkmn_center_nurse.pory"
	end
# 72 "data/scripts/pkmn_center_nurse.pory"

# 73 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 74 "data/scripts/pkmn_center_nurse.pory"
FallarborSecondaryMart::
# 75 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_BLACK_BELT
# 76 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_HARD_STONE
# 77 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_METAL_COAT
# 78 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_POISON_BARB
# 79 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SHARP_BEAK
# 80 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SILK_SCARF
# 81 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SILVER_POWDER
# 82 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SOFT_SAND
# 83 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SPELL_TAG
# 84 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 85 "data/scripts/pkmn_center_nurse.pory"
	release
# 86 "data/scripts/pkmn_center_nurse.pory"
	end
# 87 "data/scripts/pkmn_center_nurse.pory"

# 88 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 89 "data/scripts/pkmn_center_nurse.pory"
LavaridgeSecondaryMart::
# 90 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_HEAT_ROCK
# 91 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_DAMP_ROCK
# 92 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_ICY_ROCK
# 93 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SMOOTH_ROCK
# 94 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_LIGHT_CLAY
# 95 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_TERRAIN_EXTENDER
# 96 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_ROOM_SERVICE
# 97 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_ZOOM_LENS
# 98 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 99 "data/scripts/pkmn_center_nurse.pory"
	release
# 100 "data/scripts/pkmn_center_nurse.pory"
	end
# 101 "data/scripts/pkmn_center_nurse.pory"

# 102 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 103 "data/scripts/pkmn_center_nurse.pory"
FortreeSecondaryMart::
# 104 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_RED_CARD
# 105 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_BLUNDER_POLICY
# 106 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_WEAKNESS_POLICY
# 107 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_LOADED_DICE
# 108 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_AIR_BALLOON
# 109 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_ROCKY_HELMET
# 110 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_WIDE_LENS
# 111 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 112 "data/scripts/pkmn_center_nurse.pory"
	release
# 113 "data/scripts/pkmn_center_nurse.pory"
	end
# 114 "data/scripts/pkmn_center_nurse.pory"

# 115 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 116 "data/scripts/pkmn_center_nurse.pory"
MossdeepSecondaryMart::
# 117 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_WHITE_HERB
# 118 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_POWER_HERB
# 119 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_SHED_SHELL
# 120 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_THROAT_SPRAY
# 121 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_EXPERT_BELT
# 122 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 123 "data/scripts/pkmn_center_nurse.pory"
	release
# 124 "data/scripts/pkmn_center_nurse.pory"
	end
# 125 "data/scripts/pkmn_center_nurse.pory"

# 126 "data/scripts/pkmn_center_nurse.pory"
.align 2
# 127 "data/scripts/pkmn_center_nurse.pory"
SootopolisSecondaryMart::
# 128 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_PROTECTIVE_PADS
# 129 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_RING_TARGET
# 130 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_CLEAR_AMULET
# 131 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_IRON_BALL
# 132 "data/scripts/pkmn_center_nurse.pory"
	.2byte ITEM_NONE
# 133 "data/scripts/pkmn_center_nurse.pory"
	release
# 134 "data/scripts/pkmn_center_nurse.pory"
	end
# 135 "data/scripts/pkmn_center_nurse.pory"

# 136 "data/scripts/pkmn_center_nurse.pory"
Common_EventScript_PkmnCenterNurse::
# 137 "data/scripts/pkmn_center_nurse.pory"
	lock
# 138 "data/scripts/pkmn_center_nurse.pory"
	faceplayer
# 139 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 0
# 140 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_RESULT, CountPlayerTrainerStars
# 141 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_RESULT, 4, EventScript_PkmnCenterNurse_GoldCard
# 142 "data/scripts/pkmn_center_nurse.pory"

# 143 "data/scripts/pkmn_center_nurse.pory"
	goto EventScript_PkmnCenterNurse_HealPkmn
# 144 "data/scripts/pkmn_center_nurse.pory"
	end
# 145 "data/scripts/pkmn_center_nurse.pory"

# 146 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_Goodbye::
# 147 "data/scripts/pkmn_center_nurse.pory"
	return
# 148 "data/scripts/pkmn_center_nurse.pory"

# 149 "data/scripts/pkmn_center_nurse.pory"
@ VAR_0x8004 is 1 when player has Gold Card; jumps are identical
# 150 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_HealPkmn::
# 151 "data/scripts/pkmn_center_nurse.pory"
	incrementgamestat GAME_STAT_USED_POKECENTER
# 152 "data/scripts/pkmn_center_nurse.pory"
	call EventScript_PkmnCenterNurse_TakeAndHealPkmn
# 153 "data/scripts/pkmn_center_nurse.pory"
	end
# 154 "data/scripts/pkmn_center_nurse.pory"

# 155 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_IllTakeYourPkmn::
# 156 "data/scripts/pkmn_center_nurse.pory"
	message gText_IllTakeYourPkmn
# 157 "data/scripts/pkmn_center_nurse.pory"
	return
# 158 "data/scripts/pkmn_center_nurse.pory"

# 159 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_IllTakeYourPkmn2::
# 160 "data/scripts/pkmn_center_nurse.pory"
	message gText_IllTakeYourPkmn2
# 161 "data/scripts/pkmn_center_nurse.pory"
	return
# 162 "data/scripts/pkmn_center_nurse.pory"

# 163 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_TakeAndHealPkmn::
# 164 "data/scripts/pkmn_center_nurse.pory"
	applymovement VAR_0x800B, Movement_PkmnCenterNurse_Turn @ Changed from Common_Movement_WalkInPlaceFasterLeft to force the follower to enter their Poké Ball
# 165 "data/scripts/pkmn_center_nurse.pory"
	waitmovement 0
# 166 "data/scripts/pkmn_center_nurse.pory"
	dofieldeffect FLDEFF_POKECENTER_HEAL
# 167 "data/scripts/pkmn_center_nurse.pory"
.if OW_UNION_DISABLE_CHECK == FALSE && OW_FLAG_MOVE_UNION_ROOM_CHECK != 0
# 168 "data/scripts/pkmn_center_nurse.pory"
	setflag OW_FLAG_MOVE_UNION_ROOM_CHECK
# 169 "data/scripts/pkmn_center_nurse.pory"
	call CableClub_OnResume
# 170 "data/scripts/pkmn_center_nurse.pory"
	clearflag OW_FLAG_MOVE_UNION_ROOM_CHECK
# 171 "data/scripts/pkmn_center_nurse.pory"
.endif
# 172 "data/scripts/pkmn_center_nurse.pory"
	waitfieldeffect FLDEFF_POKECENTER_HEAL
# 173 "data/scripts/pkmn_center_nurse.pory"
	applymovement VAR_0x800B, Common_Movement_WalkInPlaceFasterDown
# 174 "data/scripts/pkmn_center_nurse.pory"
	waitmovement 0
# 175 "data/scripts/pkmn_center_nurse.pory"
	special HealPlayerParty
# 176 "data/scripts/pkmn_center_nurse.pory"
	callnative UpdateFollowingPokemon
# 177 "data/scripts/pkmn_center_nurse.pory"
	return
# 178 "data/scripts/pkmn_center_nurse.pory"

# 179 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_CheckTrainerHillAndUnionRoom::
# 180 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_RESULT, PlayerNotAtTrainerHillEntrance
# 181 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_RESULT, 0, EventScript_PkmnCenterNurse_ReturnPkmn
# 182 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_RESULT, BufferUnionRoomPlayerName
# 183 "data/scripts/pkmn_center_nurse.pory"
	copyvar VAR_0x8008, VAR_RESULT
# 184 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_0x8008, 0, EventScript_PkmnCenterNurse_ReturnPkmn
# 185 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_0x8008, 1, EventScript_PkmnCenterNurse_PlayerWaitingInUnionRoom
# 186 "data/scripts/pkmn_center_nurse.pory"
	end
# 187 "data/scripts/pkmn_center_nurse.pory"

# 188 "data/scripts/pkmn_center_nurse.pory"
@ VAR_0x8004 is 1 when player has Gold Card
# 189 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_ReturnPkmn::
# 190 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_0x8004, 1, EventScript_PkmnCenterNurse_ReturnPkmn2
# 191 "data/scripts/pkmn_center_nurse.pory"
	message gText_RestoredPkmnToFullHealth
# 192 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 193 "data/scripts/pkmn_center_nurse.pory"
	applymovement VAR_0x800B, Movement_PkmnCenterNurse_Bow
# 194 "data/scripts/pkmn_center_nurse.pory"
	waitmovement 0
# 195 "data/scripts/pkmn_center_nurse.pory"
	message gText_WeHopeToSeeYouAgain
# 196 "data/scripts/pkmn_center_nurse.pory"
	return
# 197 "data/scripts/pkmn_center_nurse.pory"

# 198 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_ReturnPkmn2::
# 199 "data/scripts/pkmn_center_nurse.pory"
	message gText_ThankYouForWaiting
# 200 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 201 "data/scripts/pkmn_center_nurse.pory"
	applymovement VAR_0x800B, Movement_PkmnCenterNurse_Bow
# 202 "data/scripts/pkmn_center_nurse.pory"
	waitmovement 0
# 203 "data/scripts/pkmn_center_nurse.pory"
	message gText_WeHopeToSeeYouAgain2
# 204 "data/scripts/pkmn_center_nurse.pory"
	return
# 205 "data/scripts/pkmn_center_nurse.pory"

# 206 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_PlayerWaitingInUnionRoom::
# 207 "data/scripts/pkmn_center_nurse.pory"
	goto_if_set FLAG_NURSE_UNION_ROOM_REMINDER, EventScript_PkmnCenterNurse_ReturnPkmn
# 208 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_RestoredPkmnToFullHealth, MSGBOX_DEFAULT
# 209 "data/scripts/pkmn_center_nurse.pory"
	setflag FLAG_NURSE_UNION_ROOM_REMINDER
# 210 "data/scripts/pkmn_center_nurse.pory"
	message CableClub_Text_PlayerIsWaiting
# 211 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 212 "data/scripts/pkmn_center_nurse.pory"
	applymovement VAR_0x800B, Movement_PkmnCenterNurse_Bow
# 213 "data/scripts/pkmn_center_nurse.pory"
	waitmovement 0
# 214 "data/scripts/pkmn_center_nurse.pory"
	message gText_WeHopeToSeeYouAgain
# 215 "data/scripts/pkmn_center_nurse.pory"
	return
# 216 "data/scripts/pkmn_center_nurse.pory"

# 217 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_CheckPokerus::
# 218 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_RESULT, IsPokerusInParty
# 219 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_RESULT, TRUE, EventScript_PkmnCenterNurse_ExplainPokerus
# 220 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_RESULT, FALSE, EventScript_PkmnCenterNurse_CheckTrainerHillAndUnionRoom
# 221 "data/scripts/pkmn_center_nurse.pory"
	end
# 222 "data/scripts/pkmn_center_nurse.pory"

# 223 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_ExplainPokerus::
# 224 "data/scripts/pkmn_center_nurse.pory"
	message gText_PokerusExplanation
# 225 "data/scripts/pkmn_center_nurse.pory"
	setflag FLAG_POKERUS_EXPLAINED
# 226 "data/scripts/pkmn_center_nurse.pory"
	return
# 227 "data/scripts/pkmn_center_nurse.pory"

# 228 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_GoldCard::
# 229 "data/scripts/pkmn_center_nurse.pory"
	goto_if_set FLAG_NURSE_MENTIONS_GOLD_CARD, EventScript_PkmnCenterNurse_AskForUsual
# 230 "data/scripts/pkmn_center_nurse.pory"
	setflag FLAG_NURSE_MENTIONS_GOLD_CARD
# 231 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_WelcomeCutShort, MSGBOX_DEFAULT
# 232 "data/scripts/pkmn_center_nurse.pory"
	playse SE_PIN
# 233 "data/scripts/pkmn_center_nurse.pory"
	applymovement VAR_0x800B, Common_Movement_ExclamationMark
# 234 "data/scripts/pkmn_center_nurse.pory"
	waitmovement 0
# 235 "data/scripts/pkmn_center_nurse.pory"
	applymovement VAR_0x800B, Common_Movement_Delay48
# 236 "data/scripts/pkmn_center_nurse.pory"
	waitmovement 0
# 237 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_NoticesGoldCard, MSGBOX_YESNO
# 238 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_RESULT, YES, EventScript_PkmnCenterNurse_GoldCardHealPkmn
# 239 "data/scripts/pkmn_center_nurse.pory"
	message gText_WeHopeToSeeYouAgain2
# 240 "data/scripts/pkmn_center_nurse.pory"
	return
# 241 "data/scripts/pkmn_center_nurse.pory"

# 242 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_AskForUsual::
# 243 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_YouWantTheUsual, MSGBOX_YESNO
# 244 "data/scripts/pkmn_center_nurse.pory"
	goto_if_eq VAR_RESULT, YES, EventScript_PkmnCenterNurse_GoldCardHealPkmn
# 245 "data/scripts/pkmn_center_nurse.pory"
	message gText_WeHopeToSeeYouAgain2
# 246 "data/scripts/pkmn_center_nurse.pory"
	return
# 247 "data/scripts/pkmn_center_nurse.pory"

# 248 "data/scripts/pkmn_center_nurse.pory"
EventScript_PkmnCenterNurse_GoldCardHealPkmn::
# 249 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 1
# 250 "data/scripts/pkmn_center_nurse.pory"
	goto EventScript_PkmnCenterNurse_HealPkmn
# 251 "data/scripts/pkmn_center_nurse.pory"
	end
# 252 "data/scripts/pkmn_center_nurse.pory"

# 253 "data/scripts/pkmn_center_nurse.pory"
Movement_PkmnCenterNurse_Bow:
# 254 "data/scripts/pkmn_center_nurse.pory"
	nurse_joy_bow
# 255 "data/scripts/pkmn_center_nurse.pory"
	delay_4
# 256 "data/scripts/pkmn_center_nurse.pory"
	step_end
# 257 "data/scripts/pkmn_center_nurse.pory"

# 258 "data/scripts/pkmn_center_nurse.pory"
Movement_PkmnCenterNurse_Turn:
# 259 "data/scripts/pkmn_center_nurse.pory"
	walk_in_place_faster_left
# 260 "data/scripts/pkmn_center_nurse.pory"
	step_end

EventScript_NatureMintNPC::
# 264 "data/scripts/pkmn_center_nurse.pory"
	lock
# 265 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_0
# 266 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 267 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_2
EventScript_NatureMintNPC_1:
# 270 "data/scripts/pkmn_center_nurse.pory"
	checkitem ITEM_BLANK_MINT, 1
# 271 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_ne EventScript_NatureMintNPC_5
EventScript_NatureMintNPC_4:
# 275 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_NatureMintNPC_Text_2
# 276 "data/scripts/pkmn_center_nurse.pory"
	multichoicegrid 10, 4, MULTI_STAT_NAMES_NO_HP, 2, 0
# 277 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 5
	goto_if_eq EventScript_NatureMintNPC_8
# 280 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_9
# 283 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_eq EventScript_NatureMintNPC_10
# 286 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 2
	goto_if_eq EventScript_NatureMintNPC_11
# 289 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 3
	goto_if_eq EventScript_NatureMintNPC_12
# 292 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 4
	goto_if_eq EventScript_NatureMintNPC_13
EventScript_NatureMintNPC_7:
# 295 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_NatureMintNPC_Text_3
# 296 "data/scripts/pkmn_center_nurse.pory"
	multichoicegrid 8, 4, MULTI_STAT_NAMES_NO_HP, 2, 0
# 297 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 5
	goto_if_eq EventScript_NatureMintNPC_21
# 300 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_22
# 303 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_eq EventScript_NatureMintNPC_23
# 306 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 2
	goto_if_eq EventScript_NatureMintNPC_24
# 309 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 3
	goto_if_eq EventScript_NatureMintNPC_25
# 312 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 4
	goto_if_eq EventScript_NatureMintNPC_26
EventScript_NatureMintNPC_20:
# 315 "data/scripts/pkmn_center_nurse.pory"
	compare RAISE, 0
	goto_if_eq EventScript_NatureMintNPC_36
EventScript_NatureMintNPC_35:
# 316 "data/scripts/pkmn_center_nurse.pory"
	compare RAISE, 1
	goto_if_eq EventScript_NatureMintNPC_40
EventScript_NatureMintNPC_39:
# 317 "data/scripts/pkmn_center_nurse.pory"
	compare RAISE, 2
	goto_if_eq EventScript_NatureMintNPC_44
EventScript_NatureMintNPC_43:
# 318 "data/scripts/pkmn_center_nurse.pory"
	compare RAISE, 3
	goto_if_eq EventScript_NatureMintNPC_48
EventScript_NatureMintNPC_47:
# 319 "data/scripts/pkmn_center_nurse.pory"
	compare RAISE, 4
	goto_if_eq EventScript_NatureMintNPC_51
EventScript_NatureMintNPC_33:
# 327 "data/scripts/pkmn_center_nurse.pory"
	switch RAISE
# 328 "data/scripts/pkmn_center_nurse.pory"
	case 0, EventScript_NatureMintNPC_56
# 365 "data/scripts/pkmn_center_nurse.pory"
	case 1, EventScript_NatureMintNPC_57
# 402 "data/scripts/pkmn_center_nurse.pory"
	case 2, EventScript_NatureMintNPC_58
# 439 "data/scripts/pkmn_center_nurse.pory"
	case 3, EventScript_NatureMintNPC_59
# 476 "data/scripts/pkmn_center_nurse.pory"
	case 4, EventScript_NatureMintNPC_60
EventScript_NatureMintNPC_54:
# 514 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

EventScript_NatureMintNPC_2:
# 268 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_1

EventScript_NatureMintNPC_5:
# 272 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_NatureMintNPC_Text_1
# 273 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_4

EventScript_NatureMintNPC_8:
# 278 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_7

EventScript_NatureMintNPC_9:
# 281 "data/scripts/pkmn_center_nurse.pory"
	setvar RAISE, 0
	goto EventScript_NatureMintNPC_7

EventScript_NatureMintNPC_10:
# 284 "data/scripts/pkmn_center_nurse.pory"
	setvar RAISE, 1
	goto EventScript_NatureMintNPC_7

EventScript_NatureMintNPC_11:
# 287 "data/scripts/pkmn_center_nurse.pory"
	setvar RAISE, 2
	goto EventScript_NatureMintNPC_7

EventScript_NatureMintNPC_12:
# 290 "data/scripts/pkmn_center_nurse.pory"
	setvar RAISE, 3
	goto EventScript_NatureMintNPC_7

EventScript_NatureMintNPC_13:
# 293 "data/scripts/pkmn_center_nurse.pory"
	setvar RAISE, 4
	goto EventScript_NatureMintNPC_7

EventScript_NatureMintNPC_21:
# 298 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_20

EventScript_NatureMintNPC_22:
# 301 "data/scripts/pkmn_center_nurse.pory"
	setvar LOWER, 0
	goto EventScript_NatureMintNPC_20

EventScript_NatureMintNPC_23:
# 304 "data/scripts/pkmn_center_nurse.pory"
	setvar LOWER, 1
	goto EventScript_NatureMintNPC_20

EventScript_NatureMintNPC_24:
# 307 "data/scripts/pkmn_center_nurse.pory"
	setvar LOWER, 2
	goto EventScript_NatureMintNPC_20

EventScript_NatureMintNPC_25:
# 310 "data/scripts/pkmn_center_nurse.pory"
	setvar LOWER, 3
	goto EventScript_NatureMintNPC_20

EventScript_NatureMintNPC_26:
# 313 "data/scripts/pkmn_center_nurse.pory"
	setvar LOWER, 4
	goto EventScript_NatureMintNPC_20

EventScript_NatureMintNPC_34:
# 320 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_4
# 321 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 322 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_eq EventScript_NatureMintNPC_61
	goto EventScript_NatureMintNPC_33

EventScript_NatureMintNPC_36:
# 315 "data/scripts/pkmn_center_nurse.pory"
	compare LOWER, 0
	goto_if_eq EventScript_NatureMintNPC_34
	goto EventScript_NatureMintNPC_35

EventScript_NatureMintNPC_40:
# 316 "data/scripts/pkmn_center_nurse.pory"
	compare LOWER, 1
	goto_if_eq EventScript_NatureMintNPC_34
	goto EventScript_NatureMintNPC_39

EventScript_NatureMintNPC_44:
# 317 "data/scripts/pkmn_center_nurse.pory"
	compare LOWER, 2
	goto_if_eq EventScript_NatureMintNPC_34
	goto EventScript_NatureMintNPC_43

EventScript_NatureMintNPC_48:
# 318 "data/scripts/pkmn_center_nurse.pory"
	compare LOWER, 3
	goto_if_eq EventScript_NatureMintNPC_34
	goto EventScript_NatureMintNPC_47

EventScript_NatureMintNPC_51:
# 319 "data/scripts/pkmn_center_nurse.pory"
	compare LOWER, 4
	goto_if_eq EventScript_NatureMintNPC_34
	goto EventScript_NatureMintNPC_33

EventScript_NatureMintNPC_56:
# 329 "data/scripts/pkmn_center_nurse.pory"
	switch LOWER
# 330 "data/scripts/pkmn_center_nurse.pory"
	case 1, EventScript_NatureMintNPC_64
# 338 "data/scripts/pkmn_center_nurse.pory"
	case 2, EventScript_NatureMintNPC_65
# 346 "data/scripts/pkmn_center_nurse.pory"
	case 3, EventScript_NatureMintNPC_66
# 354 "data/scripts/pkmn_center_nurse.pory"
	case 4, EventScript_NatureMintNPC_67
# 363 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_57:
# 366 "data/scripts/pkmn_center_nurse.pory"
	switch LOWER
# 367 "data/scripts/pkmn_center_nurse.pory"
	case 0, EventScript_NatureMintNPC_70
# 375 "data/scripts/pkmn_center_nurse.pory"
	case 2, EventScript_NatureMintNPC_71
# 383 "data/scripts/pkmn_center_nurse.pory"
	case 3, EventScript_NatureMintNPC_72
# 391 "data/scripts/pkmn_center_nurse.pory"
	case 4, EventScript_NatureMintNPC_73
# 400 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_58:
# 403 "data/scripts/pkmn_center_nurse.pory"
	switch LOWER
# 404 "data/scripts/pkmn_center_nurse.pory"
	case 0, EventScript_NatureMintNPC_76
# 412 "data/scripts/pkmn_center_nurse.pory"
	case 1, EventScript_NatureMintNPC_77
# 420 "data/scripts/pkmn_center_nurse.pory"
	case 3, EventScript_NatureMintNPC_78
# 428 "data/scripts/pkmn_center_nurse.pory"
	case 4, EventScript_NatureMintNPC_79
# 437 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_59:
# 440 "data/scripts/pkmn_center_nurse.pory"
	switch LOWER
# 441 "data/scripts/pkmn_center_nurse.pory"
	case 0, EventScript_NatureMintNPC_82
# 449 "data/scripts/pkmn_center_nurse.pory"
	case 1, EventScript_NatureMintNPC_83
# 457 "data/scripts/pkmn_center_nurse.pory"
	case 2, EventScript_NatureMintNPC_84
# 465 "data/scripts/pkmn_center_nurse.pory"
	case 4, EventScript_NatureMintNPC_85
# 474 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_60:
# 477 "data/scripts/pkmn_center_nurse.pory"
	switch LOWER
# 478 "data/scripts/pkmn_center_nurse.pory"
	case 0, EventScript_NatureMintNPC_88
# 486 "data/scripts/pkmn_center_nurse.pory"
	case 1, EventScript_NatureMintNPC_89
# 494 "data/scripts/pkmn_center_nurse.pory"
	case 2, EventScript_NatureMintNPC_90
# 502 "data/scripts/pkmn_center_nurse.pory"
	case 3, EventScript_NatureMintNPC_91
# 511 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_61:
# 323 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_SERIOUS_MINT
# 324 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_33

EventScript_NatureMintNPC_64:
# 331 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_5
# 332 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 333 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_94
EventScript_NatureMintNPC_93:
# 336 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_LONELY_MINT
# 337 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_65:
# 339 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_6
# 340 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 341 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_97
EventScript_NatureMintNPC_96:
# 344 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_ADAMANT_MINT
# 345 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_66:
# 347 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_7
# 348 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 349 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_100
EventScript_NatureMintNPC_99:
# 352 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_NAUGHTY_MINT
# 353 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_67:
# 355 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_8
# 356 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 357 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_103
EventScript_NatureMintNPC_102:
# 360 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_BRAVE_MINT
# 361 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_70:
# 368 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_9
# 369 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 370 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_106
EventScript_NatureMintNPC_105:
# 373 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_BOLD_MINT
# 374 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_71:
# 376 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_10
# 377 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 378 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_109
EventScript_NatureMintNPC_108:
# 381 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_IMPISH_MINT
# 382 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_72:
# 384 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_11
# 385 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 386 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_112
EventScript_NatureMintNPC_111:
# 389 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_LAX_MINT
# 390 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_73:
# 392 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_12
# 393 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 394 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_115
EventScript_NatureMintNPC_114:
# 397 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_RELAXED_MINT
# 398 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_76:
# 405 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_13
# 406 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 407 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_118
EventScript_NatureMintNPC_117:
# 410 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_MODEST_MINT
# 411 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_77:
# 413 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_14
# 414 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 415 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_121
EventScript_NatureMintNPC_120:
# 418 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_MILD_MINT
# 419 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_78:
# 421 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_15
# 422 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 423 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_124
EventScript_NatureMintNPC_123:
# 426 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_RASH_MINT
# 427 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_79:
# 429 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_16
# 430 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 431 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_127
EventScript_NatureMintNPC_126:
# 434 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_QUIET_MINT
# 435 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_82:
# 442 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_17
# 443 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 444 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_130
EventScript_NatureMintNPC_129:
# 447 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_CALM_MINT
# 448 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_83:
# 450 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_18
# 451 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 452 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_133
EventScript_NatureMintNPC_132:
# 455 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_GENTLE_MINT
# 456 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_84:
# 458 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_19
# 459 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 460 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_136
EventScript_NatureMintNPC_135:
# 463 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_CAREFUL_MINT
# 464 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_85:
# 466 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_20
# 467 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 468 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_139
EventScript_NatureMintNPC_138:
# 471 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_SASSY_MINT
# 472 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_88:
# 479 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_21
# 480 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 481 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_142
EventScript_NatureMintNPC_141:
# 484 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_TIMID_MINT
# 485 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_89:
# 487 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_22
# 488 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 489 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_145
EventScript_NatureMintNPC_144:
# 492 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_HASTY_MINT
# 493 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_90:
# 495 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_23
# 496 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 497 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_148
EventScript_NatureMintNPC_147:
# 500 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_JOLLY_MINT
# 501 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_91:
# 503 "data/scripts/pkmn_center_nurse.pory"
	message EventScript_NatureMintNPC_Text_24
# 504 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 5, 2
# 505 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_NatureMintNPC_151
EventScript_NatureMintNPC_150:
# 508 "data/scripts/pkmn_center_nurse.pory"
	giveitem ITEM_NAIVE_MINT
# 509 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BLANK_MINT, 1
	goto EventScript_NatureMintNPC_54

EventScript_NatureMintNPC_94:
# 334 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_93

EventScript_NatureMintNPC_97:
# 342 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_96

EventScript_NatureMintNPC_100:
# 350 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_99

EventScript_NatureMintNPC_103:
# 358 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_102

EventScript_NatureMintNPC_106:
# 371 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_105

EventScript_NatureMintNPC_109:
# 379 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_108

EventScript_NatureMintNPC_112:
# 387 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_111

EventScript_NatureMintNPC_115:
# 395 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_114

EventScript_NatureMintNPC_118:
# 408 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_117

EventScript_NatureMintNPC_121:
# 416 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_120

EventScript_NatureMintNPC_124:
# 424 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_123

EventScript_NatureMintNPC_127:
# 432 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_126

EventScript_NatureMintNPC_130:
# 445 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_129

EventScript_NatureMintNPC_133:
# 453 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_132

EventScript_NatureMintNPC_136:
# 461 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_135

EventScript_NatureMintNPC_139:
# 469 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_138

EventScript_NatureMintNPC_142:
# 482 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_141

EventScript_NatureMintNPC_145:
# 490 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_144

EventScript_NatureMintNPC_148:
# 498 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_147

EventScript_NatureMintNPC_151:
# 506 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_NatureMintNPC_150


EventScript_PreDamageNPC::
# 518 "data/scripts/pkmn_center_nurse.pory"
	lock
# 519 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_0
# 520 "data/scripts/pkmn_center_nurse.pory"
	multichoice 10, 4, MULTI_PREDAMAGE, 0
# 521 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_PreDamageNPC_2
# 541 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_eq EventScript_PreDamageNPC_3
EventScript_PreDamageNPC_1:
# 663 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

EventScript_PreDamageNPC_2:
# 522 "data/scripts/pkmn_center_nurse.pory"
	special ChoosePartyMon
# 523 "data/scripts/pkmn_center_nurse.pory"
	waitstate
# 524 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
# 525 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, SPECIES_EGG
	goto_if_eq EventScript_PreDamageNPC_7
EventScript_PreDamageNPC_6:
# 529 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonFainted
# 530 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_13
EventScript_PreDamageNPC_12:
# 534 "data/scripts/pkmn_center_nurse.pory"
	call Common_ShowSelectDamageScreen
# 535 "data/scripts/pkmn_center_nurse.pory"
	waitstate
# 536 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 537 "data/scripts/pkmn_center_nurse.pory"
	playmoncry 0x8007, 0
# 538 "data/scripts/pkmn_center_nurse.pory"
	waitmoncry
# 539 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_3
	goto EventScript_PreDamageNPC_1

EventScript_PreDamageNPC_3:
# 542 "data/scripts/pkmn_center_nurse.pory"
	special ChoosePartyMon
# 543 "data/scripts/pkmn_center_nurse.pory"
	waitstate
# 544 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
# 545 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, SPECIES_EGG
	goto_if_eq EventScript_PreDamageNPC_10
EventScript_PreDamageNPC_9:
# 549 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonFainted
# 550 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_16
EventScript_PreDamageNPC_15:
# 554 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_6
# 555 "data/scripts/pkmn_center_nurse.pory"
	multichoicegrid 8, 4, MULTI_STATUSES, 2, 0
# 556 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_PreDamageNPC_19
# 558 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_eq EventScript_PreDamageNPC_20
# 560 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 2
	goto_if_eq EventScript_PreDamageNPC_21
# 562 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 3
	goto_if_eq EventScript_PreDamageNPC_22
# 564 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 4
	goto_if_eq EventScript_PreDamageNPC_23
# 566 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 5
	goto_if_eq EventScript_PreDamageNPC_24
EventScript_PreDamageNPC_18:
# 569 "data/scripts/pkmn_center_nurse.pory"
	switch STATUS
# 570 "data/scripts/pkmn_center_nurse.pory"
	case 0, EventScript_PreDamageNPC_32
# 592 "data/scripts/pkmn_center_nurse.pory"
	case 1, EventScript_PreDamageNPC_33
# 603 "data/scripts/pkmn_center_nurse.pory"
	case 2, EventScript_PreDamageNPC_34
# 615 "data/scripts/pkmn_center_nurse.pory"
	case 3, EventScript_PreDamageNPC_35
# 626 "data/scripts/pkmn_center_nurse.pory"
	case 4, EventScript_PreDamageNPC_36
# 637 "data/scripts/pkmn_center_nurse.pory"
	case 5, EventScript_PreDamageNPC_37
# 660 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_1

EventScript_PreDamageNPC_7:
# 526 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_1
# 527 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_6

EventScript_PreDamageNPC_10:
# 546 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_4
# 547 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_9

EventScript_PreDamageNPC_13:
# 531 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_2
# 532 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_12

EventScript_PreDamageNPC_16:
# 551 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_5
# 552 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_15

EventScript_PreDamageNPC_19:
# 557 "data/scripts/pkmn_center_nurse.pory"
	setvar STATUS, 0
	goto EventScript_PreDamageNPC_18

EventScript_PreDamageNPC_20:
# 559 "data/scripts/pkmn_center_nurse.pory"
	setvar STATUS, 1
	goto EventScript_PreDamageNPC_18

EventScript_PreDamageNPC_21:
# 561 "data/scripts/pkmn_center_nurse.pory"
	setvar STATUS, 2
	goto EventScript_PreDamageNPC_18

EventScript_PreDamageNPC_22:
# 563 "data/scripts/pkmn_center_nurse.pory"
	setvar STATUS, 3
	goto EventScript_PreDamageNPC_18

EventScript_PreDamageNPC_23:
# 565 "data/scripts/pkmn_center_nurse.pory"
	setvar STATUS, 4
	goto EventScript_PreDamageNPC_18

EventScript_PreDamageNPC_24:
# 567 "data/scripts/pkmn_center_nurse.pory"
	setvar STATUS, 5
	goto EventScript_PreDamageNPC_18

EventScript_PreDamageNPC_32:
# 571 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonSteelType
# 572 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_40
EventScript_PreDamageNPC_39:
# 579 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonPoisonType
# 580 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_58
EventScript_PreDamageNPC_57:
# 587 "data/scripts/pkmn_center_nurse.pory"
	setstatus1 STATUS1_POISON, VAR_0x8004
# 588 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 589 "data/scripts/pkmn_center_nurse.pory"
	playmoncry 0x8007, 0
# 590 "data/scripts/pkmn_center_nurse.pory"
	waitmoncry
# 591 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_9
	goto EventScript_PreDamageNPC_1

EventScript_PreDamageNPC_33:
# 593 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonElectricType
# 594 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_43
EventScript_PreDamageNPC_42:
# 598 "data/scripts/pkmn_center_nurse.pory"
	setstatus1 STATUS1_PARALYSIS, VAR_0x8004
# 599 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 600 "data/scripts/pkmn_center_nurse.pory"
	playmoncry 0x8007, 0
# 601 "data/scripts/pkmn_center_nurse.pory"
	waitmoncry
# 602 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_11
	goto EventScript_PreDamageNPC_1

EventScript_PreDamageNPC_34:
# 604 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonImmuneToSleepDueToAbility
# 605 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_46
EventScript_PreDamageNPC_45:
# 610 "data/scripts/pkmn_center_nurse.pory"
	setstatus1 STATUS1_SLEEP_TURN ( 1 ), VAR_0x8004
# 611 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 612 "data/scripts/pkmn_center_nurse.pory"
	playmoncry 0x8007, 0
# 613 "data/scripts/pkmn_center_nurse.pory"
	waitmoncry
# 614 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_13
	goto EventScript_PreDamageNPC_1

EventScript_PreDamageNPC_35:
# 616 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonFireType
# 617 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_49
EventScript_PreDamageNPC_48:
# 621 "data/scripts/pkmn_center_nurse.pory"
	setstatus1 STATUS1_BURN, VAR_0x8004
# 622 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 623 "data/scripts/pkmn_center_nurse.pory"
	playmoncry 0x8007, 0
# 624 "data/scripts/pkmn_center_nurse.pory"
	waitmoncry
# 625 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_15
	goto EventScript_PreDamageNPC_1

EventScript_PreDamageNPC_36:
# 627 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonIceType
# 628 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_52
EventScript_PreDamageNPC_51:
# 632 "data/scripts/pkmn_center_nurse.pory"
	setstatus1 STATUS1_FREEZE, VAR_0x8004
# 633 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 634 "data/scripts/pkmn_center_nurse.pory"
	playmoncry 0x8007, 0
# 635 "data/scripts/pkmn_center_nurse.pory"
	waitmoncry
# 636 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_17
	goto EventScript_PreDamageNPC_1

EventScript_PreDamageNPC_37:
# 638 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonSteelType
# 639 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_55
EventScript_PreDamageNPC_54:
# 646 "data/scripts/pkmn_center_nurse.pory"
	special IsChosenMonPoisonType
# 647 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EventScript_PreDamageNPC_63
EventScript_PreDamageNPC_62:
# 654 "data/scripts/pkmn_center_nurse.pory"
	setstatus1 STATUS1_TOXIC_POISON, VAR_0x8004
# 655 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 656 "data/scripts/pkmn_center_nurse.pory"
	playmoncry 0x8007, 0
# 657 "data/scripts/pkmn_center_nurse.pory"
	waitmoncry
# 658 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_20
	goto EventScript_PreDamageNPC_1

EventScript_PreDamageNPC_40:
# 573 "data/scripts/pkmn_center_nurse.pory"
	getseenmon 757
# 574 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq EventScript_PreDamageNPC_60
	goto EventScript_PreDamageNPC_39

EventScript_PreDamageNPC_43:
# 595 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_10
# 596 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_42

EventScript_PreDamageNPC_46:
# 606 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 607 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_12
# 608 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_45

EventScript_PreDamageNPC_49:
# 618 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_14
# 619 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_48

EventScript_PreDamageNPC_52:
# 629 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_16
# 630 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_51

EventScript_PreDamageNPC_55:
# 640 "data/scripts/pkmn_center_nurse.pory"
	getseenmon 757
# 641 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq EventScript_PreDamageNPC_65
	goto EventScript_PreDamageNPC_54

EventScript_PreDamageNPC_58:
# 581 "data/scripts/pkmn_center_nurse.pory"
	getseenmon 757
# 582 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq EventScript_PreDamageNPC_67
	goto EventScript_PreDamageNPC_57

EventScript_PreDamageNPC_60:
# 575 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_7
# 576 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_39

EventScript_PreDamageNPC_63:
# 648 "data/scripts/pkmn_center_nurse.pory"
	getseenmon 757
# 649 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq EventScript_PreDamageNPC_69
	goto EventScript_PreDamageNPC_62

EventScript_PreDamageNPC_65:
# 642 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_18
# 643 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_54

EventScript_PreDamageNPC_67:
# 583 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_8
# 584 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_57

EventScript_PreDamageNPC_69:
# 650 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_PreDamageNPC_Text_19
# 651 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_PreDamageNPC_62


EventScript_HyperTrainNPC::
# 667 "data/scripts/pkmn_center_nurse.pory"
	lock
# 668 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_HyperTrainNPC_Text_0
# 669 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 670 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_HyperTrainNPC_2
EventScript_HyperTrainNPC_1:
# 673 "data/scripts/pkmn_center_nurse.pory"
	checkitem ITEM_BOTTLE_CAP, 1
# 674 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_ne EventScript_HyperTrainNPC_5
EventScript_HyperTrainNPC_4:
# 678 "data/scripts/pkmn_center_nurse.pory"
	special ChoosePartyMon
# 679 "data/scripts/pkmn_center_nurse.pory"
	waitstate
# 680 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_RESULT, ScriptGetPartyMonSpecies
# 681 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, SPECIES_EGG
	goto_if_eq EventScript_HyperTrainNPC_8
EventScript_HyperTrainNPC_7:
# 685 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_HyperTrainNPC_Text_3
# 686 "data/scripts/pkmn_center_nurse.pory"
	multichoicegrid 10, 4, MULTI_STAT_NAMES, 2, 0
# 687 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_HyperTrainNPC_11
# 692 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_eq EventScript_HyperTrainNPC_12
# 697 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 2
	goto_if_eq EventScript_HyperTrainNPC_13
# 702 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 3
	goto_if_eq EventScript_HyperTrainNPC_14
# 707 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 4
	goto_if_eq EventScript_HyperTrainNPC_15
# 712 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 5
	goto_if_eq EventScript_HyperTrainNPC_16
EventScript_HyperTrainNPC_10:
# 717 "data/scripts/pkmn_center_nurse.pory"
	sethypertrainstat STAT
# 718 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 719 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq EventScript_HyperTrainNPC_24
EventScript_HyperTrainNPC_23:
# 723 "data/scripts/pkmn_center_nurse.pory"
	switch STAT
# 725 "data/scripts/pkmn_center_nurse.pory"
	case 0, EventScript_HyperTrainNPC_28
# 727 "data/scripts/pkmn_center_nurse.pory"
	case 1, EventScript_HyperTrainNPC_29
# 729 "data/scripts/pkmn_center_nurse.pory"
	case 2, EventScript_HyperTrainNPC_30
# 731 "data/scripts/pkmn_center_nurse.pory"
	case 3, EventScript_HyperTrainNPC_31
# 733 "data/scripts/pkmn_center_nurse.pory"
	case 4, EventScript_HyperTrainNPC_32
# 735 "data/scripts/pkmn_center_nurse.pory"
	case 5, EventScript_HyperTrainNPC_33
EventScript_HyperTrainNPC_26:
# 738 "data/scripts/pkmn_center_nurse.pory"
	playmoncry 0x8007, 0
# 739 "data/scripts/pkmn_center_nurse.pory"
	waitmoncry
# 740 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_HyperTrainNPC_Text_5
# 741 "data/scripts/pkmn_center_nurse.pory"
	removeitem ITEM_BOTTLE_CAP, 1
# 742 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

EventScript_HyperTrainNPC_2:
# 671 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_HyperTrainNPC_1

EventScript_HyperTrainNPC_5:
# 675 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_HyperTrainNPC_Text_1
# 676 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_HyperTrainNPC_4

EventScript_HyperTrainNPC_8:
# 682 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_HyperTrainNPC_Text_2
# 683 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_HyperTrainNPC_7

EventScript_HyperTrainNPC_11:
# 689 "data/scripts/pkmn_center_nurse.pory"
	setvar STAT, 0
# 690 "data/scripts/pkmn_center_nurse.pory"
	canhypertrain 0, VAR_0x8004
	goto EventScript_HyperTrainNPC_10

EventScript_HyperTrainNPC_12:
# 694 "data/scripts/pkmn_center_nurse.pory"
	setvar STAT, 1
# 695 "data/scripts/pkmn_center_nurse.pory"
	canhypertrain 1, VAR_0x8004
	goto EventScript_HyperTrainNPC_10

EventScript_HyperTrainNPC_13:
# 699 "data/scripts/pkmn_center_nurse.pory"
	setvar STAT, 2
# 700 "data/scripts/pkmn_center_nurse.pory"
	canhypertrain 2, VAR_0x8004
	goto EventScript_HyperTrainNPC_10

EventScript_HyperTrainNPC_14:
# 704 "data/scripts/pkmn_center_nurse.pory"
	setvar STAT, 3
# 705 "data/scripts/pkmn_center_nurse.pory"
	canhypertrain 3, VAR_0x8004
	goto EventScript_HyperTrainNPC_10

EventScript_HyperTrainNPC_15:
# 709 "data/scripts/pkmn_center_nurse.pory"
	setvar STAT, 4
# 710 "data/scripts/pkmn_center_nurse.pory"
	canhypertrain 4, VAR_0x8004
	goto EventScript_HyperTrainNPC_10

EventScript_HyperTrainNPC_16:
# 714 "data/scripts/pkmn_center_nurse.pory"
	setvar STAT, 5
# 715 "data/scripts/pkmn_center_nurse.pory"
	canhypertrain 5, VAR_0x8004
	goto EventScript_HyperTrainNPC_10

EventScript_HyperTrainNPC_24:
# 720 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_HyperTrainNPC_Text_4
# 721 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_HyperTrainNPC_23

EventScript_HyperTrainNPC_28:
# 726 "data/scripts/pkmn_center_nurse.pory"
	hypertrain 0, VAR_0x8004
	goto EventScript_HyperTrainNPC_26

EventScript_HyperTrainNPC_29:
# 728 "data/scripts/pkmn_center_nurse.pory"
	hypertrain 1, VAR_0x8004
	goto EventScript_HyperTrainNPC_26

EventScript_HyperTrainNPC_30:
# 730 "data/scripts/pkmn_center_nurse.pory"
	hypertrain 2, VAR_0x8004
	goto EventScript_HyperTrainNPC_26

EventScript_HyperTrainNPC_31:
# 732 "data/scripts/pkmn_center_nurse.pory"
	hypertrain 3, VAR_0x8004
	goto EventScript_HyperTrainNPC_26

EventScript_HyperTrainNPC_32:
# 734 "data/scripts/pkmn_center_nurse.pory"
	hypertrain 4, VAR_0x8004
	goto EventScript_HyperTrainNPC_26

EventScript_HyperTrainNPC_33:
# 736 "data/scripts/pkmn_center_nurse.pory"
	hypertrain 5, VAR_0x8004
	goto EventScript_HyperTrainNPC_26


BPShopClerk::
# 746 "data/scripts/pkmn_center_nurse.pory"
	lockall
# 747 "data/scripts/pkmn_center_nurse.pory"
	msgbox BPShopClerk_Text_0
# 748 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 749 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 1
	goto_if_lt BPShopClerk_2
BPShopClerk_1:
# 753 "data/scripts/pkmn_center_nurse.pory"
	msgbox BPShopClerk_Text_2
# 754 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 755 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq BPShopClerk_5
BPShopClerk_4:
# 758 "data/scripts/pkmn_center_nurse.pory"
	special ShowBattlePointsWindow
# 759 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, SCROLL_MULTI_BF_EXCHANGE_CORNER_HOLD_ITEM_VENDOR
# 765 "data/scripts/pkmn_center_nurse.pory"
	special ShowFrontierExchangeCornerItemIconWindow
# 766 "data/scripts/pkmn_center_nurse.pory"
	special ShowScrollableMultichoice
# 767 "data/scripts/pkmn_center_nurse.pory"
	waitstate
# 768 "data/scripts/pkmn_center_nurse.pory"
	special CloseFrontierExchangeCornerItemIconWindow
# 769 "data/scripts/pkmn_center_nurse.pory"
	special CloseBattlePointsWindow
# 770 "data/scripts/pkmn_center_nurse.pory"
	switch VAR_RESULT
# 771 "data/scripts/pkmn_center_nurse.pory"
	case 0, BPShopClerk_9
# 773 "data/scripts/pkmn_center_nurse.pory"
	case 1, BPShopClerk_10
# 775 "data/scripts/pkmn_center_nurse.pory"
	case 2, BPShopClerk_11
# 777 "data/scripts/pkmn_center_nurse.pory"
	case 3, BPShopClerk_12
# 779 "data/scripts/pkmn_center_nurse.pory"
	case 4, BPShopClerk_13
# 781 "data/scripts/pkmn_center_nurse.pory"
	case 5, BPShopClerk_14
# 783 "data/scripts/pkmn_center_nurse.pory"
	case 6, BPShopClerk_15
# 785 "data/scripts/pkmn_center_nurse.pory"
	case 7, BPShopClerk_16
# 787 "data/scripts/pkmn_center_nurse.pory"
	case 8, BPShopClerk_17
# 789 "data/scripts/pkmn_center_nurse.pory"
	case 9, BPShopClerk_18
# 791 "data/scripts/pkmn_center_nurse.pory"
	case 10, BPShopClerk_19
# 793 "data/scripts/pkmn_center_nurse.pory"
	case 11, BPShopClerk_20
BPShopClerk_7:
# 796 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

BPShopClerk_2:
# 750 "data/scripts/pkmn_center_nurse.pory"
	msgbox BPShopClerk_Text_1
# 751 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto BPShopClerk_1

BPShopClerk_5:
# 756 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto BPShopClerk_4

BPShopClerk_9:
# 772 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyToxicOrb
	goto BPShopClerk_7

BPShopClerk_10:
# 774 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyFlameOrb
	goto BPShopClerk_7

BPShopClerk_11:
# 776 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyFocusSash
	goto BPShopClerk_7

BPShopClerk_12:
# 778 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyEjectPack
	goto BPShopClerk_7

BPShopClerk_13:
# 780 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyEjectButton
	goto BPShopClerk_7

BPShopClerk_14:
# 782 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyBlackSludge
	goto BPShopClerk_7

BPShopClerk_15:
# 784 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyLeftovers
	goto BPShopClerk_7

BPShopClerk_16:
# 786 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyAssaultVest
	goto BPShopClerk_7

BPShopClerk_17:
# 788 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyEviolite
	goto BPShopClerk_7

BPShopClerk_18:
# 790 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyAbilityPatch
	goto BPShopClerk_7

BPShopClerk_19:
# 792 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyLifeOrb
	goto BPShopClerk_7

BPShopClerk_20:
# 794 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyRareCandy
	goto BPShopClerk_7


TryBuyEviolite::
# 800 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_0
# 801 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 802 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyEviolite_2
TryBuyEviolite_1:
# 809 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_EVIOLITE
# 810 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 811 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 4
	goto_if_lt TryBuyEviolite_5
TryBuyEviolite_4:
# 815 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 816 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyEviolite_8
TryBuyEviolite_7:
# 821 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 4
# 822 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 823 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 824 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 825 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_3
# 826 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyEviolite_2:
# 803 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyEviolite_1

TryBuyEviolite_5:
# 812 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_1
# 813 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyEviolite_4

TryBuyEviolite_8:
# 817 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 818 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyEviolite_7


TryBuyRareCandy::
# 830 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyRareCandy_Text_0
# 831 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 832 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyRareCandy_2
TryBuyRareCandy_1:
# 835 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_RARE_CANDY
# 836 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 837 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 8
	goto_if_lt TryBuyRareCandy_5
TryBuyRareCandy_4:
# 841 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 842 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyRareCandy_8
TryBuyRareCandy_7:
# 846 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 1
# 847 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 848 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 849 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 850 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyRareCandy_Text_1
# 851 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyRareCandy_2:
# 833 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyRareCandy_1

TryBuyRareCandy_5:
# 838 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_1
# 839 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyRareCandy_4

TryBuyRareCandy_8:
# 843 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 844 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyRareCandy_7


TryBuyToxicOrb::
# 855 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyToxicOrb_Text_0
# 856 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 857 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyToxicOrb_2
TryBuyToxicOrb_1:
# 860 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_TOXIC_ORB
# 861 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 862 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyToxicOrb_5
TryBuyToxicOrb_4:
# 866 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 1
# 867 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 868 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 869 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 870 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyToxicOrb_Text_1
# 871 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyToxicOrb_2:
# 858 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyToxicOrb_1

TryBuyToxicOrb_5:
# 863 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 864 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyToxicOrb_4


TryBuyFlameOrb::
# 875 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFlameOrb_Text_0
# 876 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 877 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyFlameOrb_2
TryBuyFlameOrb_1:
# 880 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_FLAME_ORB
# 881 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 882 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyFlameOrb_5
TryBuyFlameOrb_4:
# 886 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 1
# 887 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 888 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 889 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 890 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFlameOrb_Text_1
# 891 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyFlameOrb_2:
# 878 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyFlameOrb_1

TryBuyFlameOrb_5:
# 883 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 884 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyFlameOrb_4


TryBuyFocusSash::
# 895 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFocusSash_Text_0
# 896 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 897 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyFocusSash_2
TryBuyFocusSash_1:
# 900 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_FOCUS_SASH
# 901 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 902 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyFocusSash_5
TryBuyFocusSash_4:
# 906 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 1
# 907 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 908 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 909 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 910 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFocusSash_Text_1
# 911 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyFocusSash_2:
# 898 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyFocusSash_1

TryBuyFocusSash_5:
# 903 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 904 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyFocusSash_4


TryBuyEjectPack::
# 915 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEjectPack_Text_0
# 916 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 917 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyEjectPack_2
TryBuyEjectPack_1:
# 920 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_EJECT_PACK
# 921 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 922 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyEjectPack_5
TryBuyEjectPack_4:
# 926 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 1
# 927 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 928 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 929 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 930 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEjectPack_Text_1
# 931 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyEjectPack_2:
# 918 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyEjectPack_1

TryBuyEjectPack_5:
# 923 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 924 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyEjectPack_4


TryBuyEjectButton::
# 935 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEjectButton_Text_0
# 936 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 937 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyEjectButton_2
TryBuyEjectButton_1:
# 940 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_EJECT_BUTTON
# 941 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 942 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 2
	goto_if_lt TryBuyEjectButton_5
TryBuyEjectButton_4:
# 946 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 947 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyEjectButton_8
TryBuyEjectButton_7:
# 951 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 2
# 952 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 953 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 954 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 955 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEjectButton_Text_1
# 956 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyEjectButton_2:
# 938 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyEjectButton_1

TryBuyEjectButton_5:
# 943 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_1
# 944 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyEjectButton_4

TryBuyEjectButton_8:
# 948 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 949 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyEjectButton_7


TryBuyBlackSludge::
# 960 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBlackSludge_Text_0
# 961 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 962 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyBlackSludge_2
TryBuyBlackSludge_1:
# 965 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_BLACK_SLUDGE
# 966 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 967 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 2
	goto_if_lt TryBuyBlackSludge_5
TryBuyBlackSludge_4:
# 971 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 972 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyBlackSludge_8
TryBuyBlackSludge_7:
# 976 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 2
# 977 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 978 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 979 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 980 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBlackSludge_Text_1
# 981 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyBlackSludge_2:
# 963 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyBlackSludge_1

TryBuyBlackSludge_5:
# 968 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_1
# 969 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyBlackSludge_4

TryBuyBlackSludge_8:
# 973 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 974 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyBlackSludge_7


TryBuyLeftovers::
# 985 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyLeftovers_Text_0
# 986 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 987 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyLeftovers_2
TryBuyLeftovers_1:
# 990 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_LEFTOVERS
# 991 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 992 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 2
	goto_if_lt TryBuyLeftovers_5
TryBuyLeftovers_4:
# 996 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 997 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyLeftovers_8
TryBuyLeftovers_7:
# 1001 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 2
# 1002 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 1003 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 1004 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 1005 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyLeftovers_Text_1
# 1006 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyLeftovers_2:
# 988 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyLeftovers_1

TryBuyLeftovers_5:
# 993 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_1
# 994 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyLeftovers_4

TryBuyLeftovers_8:
# 998 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 999 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyLeftovers_7


TryBuyAssaultVest::
# 1010 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyAssaultVest_Text_0
# 1011 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1012 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyAssaultVest_2
TryBuyAssaultVest_1:
# 1015 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_ASSAULT_VEST
# 1016 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 1017 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 2
	goto_if_lt TryBuyAssaultVest_5
TryBuyAssaultVest_4:
# 1021 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 1022 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyAssaultVest_8
TryBuyAssaultVest_7:
# 1026 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 2
# 1027 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 1028 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 1029 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 1030 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyAssaultVest_Text_1
# 1031 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyAssaultVest_2:
# 1013 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyAssaultVest_1

TryBuyAssaultVest_5:
# 1018 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_1
# 1019 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyAssaultVest_4

TryBuyAssaultVest_8:
# 1023 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 1024 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyAssaultVest_7


TryBuyAbilityPatch::
# 1035 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyAbilityPatch_Text_0
# 1036 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1037 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyAbilityPatch_2
TryBuyAbilityPatch_1:
# 1040 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_ABILITY_PATCH
# 1041 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 1042 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 4
	goto_if_lt TryBuyAbilityPatch_5
TryBuyAbilityPatch_4:
# 1046 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 1047 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyAbilityPatch_8
TryBuyAbilityPatch_7:
# 1051 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 4
# 1052 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 1053 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 1054 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 1055 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyAbilityPatch_Text_1
# 1056 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyAbilityPatch_2:
# 1038 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyAbilityPatch_1

TryBuyAbilityPatch_5:
# 1043 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_1
# 1044 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyAbilityPatch_4

TryBuyAbilityPatch_8:
# 1048 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 1049 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyAbilityPatch_7


TryBuyLifeOrb::
# 1060 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyLifeOrb_Text_0
# 1061 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1062 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyLifeOrb_2
TryBuyLifeOrb_1:
# 1065 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8009, ITEM_LIFE_ORB
# 1066 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 1067 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 6
	goto_if_lt TryBuyLifeOrb_5
TryBuyLifeOrb_4:
# 1071 "data/scripts/pkmn_center_nurse.pory"
	checkitemspace VAR_0x8009
# 1072 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyLifeOrb_8
TryBuyLifeOrb_7:
# 1076 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 6
# 1077 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 1078 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 1079 "data/scripts/pkmn_center_nurse.pory"
	additem VAR_0x8009
# 1080 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyLifeOrb_Text_1
# 1081 "data/scripts/pkmn_center_nurse.pory"
	special UpdateBattlePointsWindow
	return

TryBuyLifeOrb_2:
# 1063 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyLifeOrb_1

TryBuyLifeOrb_5:
# 1068 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_1
# 1069 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyLifeOrb_4

TryBuyLifeOrb_8:
# 1073 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyEviolite_Text_2
# 1074 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyLifeOrb_7


EggMoveTutor::
# 1085 "data/scripts/pkmn_center_nurse.pory"
	msgbox EggMoveTutor_Text_0
# 1086 "data/scripts/pkmn_center_nurse.pory"
	specialvar VAR_TEMP_1, GetFrontierBattlePoints
# 1087 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_TEMP_1, 1
	goto_if_lt EggMoveTutor_2
EggMoveTutor_1:
# 1091 "data/scripts/pkmn_center_nurse.pory"
	msgbox EggMoveTutor_Text_1
# 1092 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1093 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EggMoveTutor_5
EggMoveTutor_4:
# 1096 "data/scripts/pkmn_center_nurse.pory"
	special ChooseMonForMoveRelearner
# 1097 "data/scripts/pkmn_center_nurse.pory"
	waitstate
# 1098 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_0x8004, PARTY_NOTHING_CHOSEN
	goto_if_eq EggMoveTutor_8
EggMoveTutor_7:
# 1101 "data/scripts/pkmn_center_nurse.pory"
	special IsSelectedMonEgg
# 1102 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq EggMoveTutor_11
EggMoveTutor_10:
# 1106 "data/scripts/pkmn_center_nurse.pory"
	special DoesChosenMonHaveEggMoves
# 1107 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq EggMoveTutor_14
EggMoveTutor_13:
# 1111 "data/scripts/pkmn_center_nurse.pory"
	specialvar 0x8007, GetSelectedMonNicknameAndSpecies
# 1112 "data/scripts/pkmn_center_nurse.pory"
	msgbox EggMoveTutor_Text_4
# 1113 "data/scripts/pkmn_center_nurse.pory"
	special TeachEggMove
# 1114 "data/scripts/pkmn_center_nurse.pory"
	waitstate
# 1115 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, 1
# 1116 "data/scripts/pkmn_center_nurse.pory"
	special TakeFrontierBattlePoints
# 1117 "data/scripts/pkmn_center_nurse.pory"
	playse SE_SHOP
# 1118 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

EggMoveTutor_2:
# 1088 "data/scripts/pkmn_center_nurse.pory"
	msgbox BPShopClerk_Text_1
# 1089 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EggMoveTutor_1

EggMoveTutor_5:
# 1094 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EggMoveTutor_4

EggMoveTutor_8:
# 1099 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EggMoveTutor_7

EggMoveTutor_11:
# 1103 "data/scripts/pkmn_center_nurse.pory"
	msgbox EggMoveTutor_Text_2
# 1104 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EggMoveTutor_10

EggMoveTutor_14:
# 1108 "data/scripts/pkmn_center_nurse.pory"
	msgbox EggMoveTutor_Text_3
# 1109 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EggMoveTutor_13


EventScript_FishermanSalesman::
# 1122 "data/scripts/pkmn_center_nurse.pory"
	lockall
# 1123 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_FishermanSalesman_Text_0
# 1124 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 500
# 1125 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq EventScript_FishermanSalesman_2
EventScript_FishermanSalesman_1:
# 1129 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_FishermanSalesman_Text_2
# 1130 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1131 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq EventScript_FishermanSalesman_5
EventScript_FishermanSalesman_4:
# 1134 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_0x8004, SCROLL_MULTI_FISH
# 1135 "data/scripts/pkmn_center_nurse.pory"
	showmoneybox 0, 0
# 1136 "data/scripts/pkmn_center_nurse.pory"
	special ShowScrollableMultichoice
# 1137 "data/scripts/pkmn_center_nurse.pory"
	waitstate
# 1139 "data/scripts/pkmn_center_nurse.pory"
	switch VAR_RESULT
# 1141 "data/scripts/pkmn_center_nurse.pory"
	case 0, EventScript_FishermanSalesman_9
# 1143 "data/scripts/pkmn_center_nurse.pory"
	case 1, EventScript_FishermanSalesman_10
# 1145 "data/scripts/pkmn_center_nurse.pory"
	case 2, EventScript_FishermanSalesman_11
# 1147 "data/scripts/pkmn_center_nurse.pory"
	case 3, EventScript_FishermanSalesman_12
# 1149 "data/scripts/pkmn_center_nurse.pory"
	case 4, EventScript_FishermanSalesman_13
# 1151 "data/scripts/pkmn_center_nurse.pory"
	case 5, EventScript_FishermanSalesman_14
# 1153 "data/scripts/pkmn_center_nurse.pory"
	case 6, EventScript_FishermanSalesman_15
# 1155 "data/scripts/pkmn_center_nurse.pory"
	case 7, EventScript_FishermanSalesman_16
# 1157 "data/scripts/pkmn_center_nurse.pory"
	case 8, EventScript_FishermanSalesman_17
# 1159 "data/scripts/pkmn_center_nurse.pory"
	case 9, EventScript_FishermanSalesman_18
# 1161 "data/scripts/pkmn_center_nurse.pory"
	case 10, EventScript_FishermanSalesman_19
# 1163 "data/scripts/pkmn_center_nurse.pory"
	case 11, EventScript_FishermanSalesman_20
# 1165 "data/scripts/pkmn_center_nurse.pory"
	case 12, EventScript_FishermanSalesman_21
# 1168 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1169 "data/scripts/pkmn_center_nurse.pory"
	goto End
EventScript_FishermanSalesman_7:
# 1171 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

EventScript_FishermanSalesman_2:
# 1126 "data/scripts/pkmn_center_nurse.pory"
	msgbox EventScript_FishermanSalesman_Text_1
# 1127 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_FishermanSalesman_1

EventScript_FishermanSalesman_5:
# 1132 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto EventScript_FishermanSalesman_4

EventScript_FishermanSalesman_9:
# 1142 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyMagikarp
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_10:
# 1144 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyGoldeen
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_11:
# 1146 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyRemoraid
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_12:
# 1148 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyFeebas
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_13:
# 1150 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyFinneon
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_14:
# 1152 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyTynamo
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_15:
# 1154 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyArrokuda
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_16:
# 1156 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyBarboach
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_17:
# 1158 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyChinchou
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_18:
# 1160 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyCarvanha
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_19:
# 1162 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyQwilfish
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_20:
# 1164 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyBasculin
	goto EventScript_FishermanSalesman_7

EventScript_FishermanSalesman_21:
# 1166 "data/scripts/pkmn_center_nurse.pory"
	call TryBuyCosmog
	goto EventScript_FishermanSalesman_7


TryBuyMagikarp::
# 1175 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_0
# 1176 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1177 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyMagikarp_2
TryBuyMagikarp_1:
# 1181 "data/scripts/pkmn_center_nurse.pory"
	removemoney 500
# 1182 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1183 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_MAGIKARP, 5, ITEM_NONE, ITEM_LURE_BALL
# 1184 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyMagikarp_4
# 1189 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyMagikarp_5
# 1195 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1196 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1197 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyMagikarp_2:
# 1178 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1179 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyMagikarp_1

TryBuyMagikarp_4:
# 1185 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1186 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_1
# 1187 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyMagikarp_5:
# 1190 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1191 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_1
# 1192 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyGoldeen::
# 1202 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyGoldeen_Text_0
# 1203 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1204 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyGoldeen_2
TryBuyGoldeen_1:
# 1208 "data/scripts/pkmn_center_nurse.pory"
	removemoney 500
# 1209 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1210 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_GOLDEEN, 5, ITEM_NONE, ITEM_LURE_BALL
# 1211 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyGoldeen_4
# 1216 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyGoldeen_5
# 1222 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1223 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1224 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyGoldeen_2:
# 1205 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1206 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyGoldeen_1

TryBuyGoldeen_4:
# 1212 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1213 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyGoldeen_Text_1
# 1214 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyGoldeen_5:
# 1217 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1218 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyGoldeen_Text_1
# 1219 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyRemoraid::
# 1229 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyRemoraid_Text_0
# 1230 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1231 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyRemoraid_2
TryBuyRemoraid_1:
# 1235 "data/scripts/pkmn_center_nurse.pory"
	removemoney 500
# 1236 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1237 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_REMORAID, 5, ITEM_NONE, ITEM_LURE_BALL
# 1238 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyRemoraid_4
# 1243 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyRemoraid_5
# 1249 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1250 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1251 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyRemoraid_2:
# 1232 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1233 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyRemoraid_1

TryBuyRemoraid_4:
# 1239 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1240 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyRemoraid_Text_1
# 1241 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyRemoraid_5:
# 1244 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1245 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyRemoraid_Text_1
# 1246 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyFeebas::
# 1256 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 1000
# 1257 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyFeebas_2
TryBuyFeebas_1:
# 1262 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFeebas_Text_1
# 1263 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1264 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyFeebas_5
TryBuyFeebas_4:
# 1268 "data/scripts/pkmn_center_nurse.pory"
	removemoney 1000
# 1269 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1270 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_FEEBAS, 5, ITEM_NONE, ITEM_LURE_BALL
# 1271 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyFeebas_7
# 1276 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyFeebas_8
# 1282 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1283 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1284 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyFeebas_2:
# 1258 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFeebas_Text_0
# 1259 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1260 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyFeebas_1

TryBuyFeebas_5:
# 1265 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1266 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyFeebas_4

TryBuyFeebas_7:
# 1272 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1273 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFeebas_Text_2
# 1274 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyFeebas_8:
# 1277 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1278 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFeebas_Text_2
# 1279 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyFinneon::
# 1289 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 1000
# 1290 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyFinneon_2
TryBuyFinneon_1:
# 1295 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFinneon_Text_1
# 1296 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1297 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyFinneon_5
TryBuyFinneon_4:
# 1301 "data/scripts/pkmn_center_nurse.pory"
	removemoney 1000
# 1302 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1303 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_FINNEON, 5, ITEM_NONE, ITEM_LURE_BALL
# 1304 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyFinneon_7
# 1309 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyFinneon_8
# 1315 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1316 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1317 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyFinneon_2:
# 1291 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFinneon_Text_0
# 1292 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1293 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyFinneon_1

TryBuyFinneon_5:
# 1298 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1299 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyFinneon_4

TryBuyFinneon_7:
# 1305 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1306 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFinneon_Text_2
# 1307 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyFinneon_8:
# 1310 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1311 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyFinneon_Text_2
# 1312 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyTynamo::
# 1322 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 1000
# 1323 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyTynamo_2
TryBuyTynamo_1:
# 1328 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyTynamo_Text_1
# 1329 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1330 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyTynamo_5
TryBuyTynamo_4:
# 1334 "data/scripts/pkmn_center_nurse.pory"
	removemoney 1000
# 1335 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1336 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_TYNAMO, 5, ITEM_NONE, ITEM_LURE_BALL
# 1337 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyTynamo_7
# 1342 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyTynamo_8
# 1348 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1349 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1350 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyTynamo_2:
# 1324 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyTynamo_Text_0
# 1325 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1326 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyTynamo_1

TryBuyTynamo_5:
# 1331 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1332 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyTynamo_4

TryBuyTynamo_7:
# 1338 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1339 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyTynamo_Text_2
# 1340 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyTynamo_8:
# 1343 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1344 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyTynamo_Text_2
# 1345 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyArrokuda::
# 1355 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 1000
# 1356 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyArrokuda_2
TryBuyArrokuda_1:
# 1361 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyArrokuda_Text_1
# 1362 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1363 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyArrokuda_5
TryBuyArrokuda_4:
# 1367 "data/scripts/pkmn_center_nurse.pory"
	removemoney 1000
# 1368 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1369 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_ARROKUDA, 5, ITEM_NONE, ITEM_LURE_BALL
# 1370 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyArrokuda_7
# 1375 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyArrokuda_8
# 1381 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1382 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1383 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyArrokuda_2:
# 1357 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyArrokuda_Text_0
# 1358 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1359 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyArrokuda_1

TryBuyArrokuda_5:
# 1364 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1365 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyArrokuda_4

TryBuyArrokuda_7:
# 1371 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1372 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyArrokuda_Text_2
# 1373 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyArrokuda_8:
# 1376 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1377 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyArrokuda_Text_2
# 1378 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyBarboach::
# 1388 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 1000
# 1389 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyBarboach_2
TryBuyBarboach_1:
# 1394 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBarboach_Text_1
# 1395 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1396 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyBarboach_5
TryBuyBarboach_4:
# 1400 "data/scripts/pkmn_center_nurse.pory"
	removemoney 1000
# 1401 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1402 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_BARBOACH, 5, ITEM_NONE, ITEM_LURE_BALL
# 1403 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyBarboach_7
# 1408 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyBarboach_8
# 1414 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1415 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1416 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyBarboach_2:
# 1390 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBarboach_Text_0
# 1391 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1392 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyBarboach_1

TryBuyBarboach_5:
# 1397 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1398 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyBarboach_4

TryBuyBarboach_7:
# 1404 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1405 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBarboach_Text_2
# 1406 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyBarboach_8:
# 1409 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1410 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBarboach_Text_2
# 1411 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyChinchou::
# 1421 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 5000
# 1422 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyChinchou_2
TryBuyChinchou_1:
# 1427 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyChinchou_Text_1
# 1428 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1429 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyChinchou_5
TryBuyChinchou_4:
# 1433 "data/scripts/pkmn_center_nurse.pory"
	removemoney 5000
# 1434 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1435 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_CHINCHOU, 5, ITEM_NONE, ITEM_LURE_BALL
# 1436 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyChinchou_7
# 1441 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyChinchou_8
# 1447 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1448 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1449 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyChinchou_2:
# 1423 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyChinchou_Text_0
# 1424 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1425 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyChinchou_1

TryBuyChinchou_5:
# 1430 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1431 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyChinchou_4

TryBuyChinchou_7:
# 1437 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1438 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyChinchou_Text_2
# 1439 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyChinchou_8:
# 1442 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1443 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyChinchou_Text_2
# 1444 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyCarvanha::
# 1454 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 5000
# 1455 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyCarvanha_2
TryBuyCarvanha_1:
# 1460 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyCarvanha_Text_1
# 1461 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1462 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyCarvanha_5
TryBuyCarvanha_4:
# 1466 "data/scripts/pkmn_center_nurse.pory"
	removemoney 5000
# 1467 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1468 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_CARVANHA, 5, ITEM_NONE, ITEM_LURE_BALL
# 1469 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyCarvanha_7
# 1474 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyCarvanha_8
# 1480 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1481 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1482 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyCarvanha_2:
# 1456 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyCarvanha_Text_0
# 1457 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1458 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyCarvanha_1

TryBuyCarvanha_5:
# 1463 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1464 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyCarvanha_4

TryBuyCarvanha_7:
# 1470 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1471 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyCarvanha_Text_2
# 1472 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyCarvanha_8:
# 1475 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1476 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyCarvanha_Text_2
# 1477 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyQwilfish::
# 1487 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 10000
# 1488 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyQwilfish_2
TryBuyQwilfish_1:
# 1493 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyQwilfish_Text_1
# 1494 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1495 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyQwilfish_5
TryBuyQwilfish_4:
# 1499 "data/scripts/pkmn_center_nurse.pory"
	removemoney 10000
# 1500 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1501 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_QWILFISH_HISUI, 5, ITEM_NONE, ITEM_LURE_BALL
# 1502 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyQwilfish_7
# 1507 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyQwilfish_8
# 1513 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1514 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1515 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyQwilfish_2:
# 1489 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyQwilfish_Text_0
# 1490 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1491 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyQwilfish_1

TryBuyQwilfish_5:
# 1496 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1497 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyQwilfish_4

TryBuyQwilfish_7:
# 1503 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1504 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyQwilfish_Text_2
# 1505 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyQwilfish_8:
# 1508 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1509 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyQwilfish_Text_2
# 1510 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyBasculin::
# 1520 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 10000
# 1521 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyBasculin_2
TryBuyBasculin_1:
# 1526 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBasculin_Text_1
# 1527 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1528 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyBasculin_5
TryBuyBasculin_4:
# 1532 "data/scripts/pkmn_center_nurse.pory"
	removemoney 10000
# 1533 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1534 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_BASCULIN_WHITE_STRIPED, 5, ITEM_NONE, ITEM_LURE_BALL
# 1535 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyBasculin_7
# 1540 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyBasculin_8
# 1546 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1547 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1548 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyBasculin_2:
# 1522 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBasculin_Text_0
# 1523 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1524 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyBasculin_1

TryBuyBasculin_5:
# 1529 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1530 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyBasculin_4

TryBuyBasculin_7:
# 1536 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1537 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBasculin_Text_2
# 1538 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyBasculin_8:
# 1541 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1542 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyBasculin_Text_2
# 1543 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


TryBuyCosmog::
# 1553 "data/scripts/pkmn_center_nurse.pory"
	checkmoney 50000
# 1554 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, FALSE
	goto_if_eq TryBuyCosmog_2
TryBuyCosmog_1:
# 1559 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyCosmog_Text_1
# 1560 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1561 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 0
	goto_if_eq TryBuyCosmog_5
TryBuyCosmog_4:
# 1565 "data/scripts/pkmn_center_nurse.pory"
	removemoney 50000
# 1566 "data/scripts/pkmn_center_nurse.pory"
	updatemoneybox
# 1567 "data/scripts/pkmn_center_nurse.pory"
	givemon SPECIES_COSMOG, 5, ITEM_NONE, ITEM_LURE_BALL
# 1568 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PARTY
	goto_if_eq TryBuyCosmog_7
# 1573 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, MON_GIVEN_TO_PC
	goto_if_eq TryBuyCosmog_8
# 1579 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyMagikarp_Text_2
# 1580 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1581 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

TryBuyCosmog_2:
# 1555 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyCosmog_Text_0
# 1556 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1557 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyCosmog_1

TryBuyCosmog_5:
# 1562 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1563 "data/scripts/pkmn_center_nurse.pory"
	goto End
	goto TryBuyCosmog_4

TryBuyCosmog_7:
# 1569 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1570 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyCosmog_Text_2
# 1571 "data/scripts/pkmn_center_nurse.pory"
	call NicknamePartyMon
	return

TryBuyCosmog_8:
# 1574 "data/scripts/pkmn_center_nurse.pory"
	playfanfare MUS_OBTAIN_ITEM
# 1575 "data/scripts/pkmn_center_nurse.pory"
	msgbox TryBuyCosmog_Text_2
# 1576 "data/scripts/pkmn_center_nurse.pory"
	call NicknameBoxMon
	return


NicknamePartyMon::
# 1586 "data/scripts/pkmn_center_nurse.pory"
	msgbox NicknamePartyMon_Text_0
# 1587 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1588 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_eq NicknamePartyMon_2
NicknamePartyMon_1:
# 1592 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1593 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

NicknamePartyMon_2:
# 1589 "data/scripts/pkmn_center_nurse.pory"
	call Common_EventScript_GetGiftMonPartySlot
# 1590 "data/scripts/pkmn_center_nurse.pory"
	call Common_EventScript_GetGiftMonPartySlot
	goto NicknamePartyMon_1


NicknameBoxMon::
# 1597 "data/scripts/pkmn_center_nurse.pory"
	msgbox NicknamePartyMon_Text_0
# 1598 "data/scripts/pkmn_center_nurse.pory"
	yesnobox 8, 4
# 1599 "data/scripts/pkmn_center_nurse.pory"
	compare VAR_RESULT, 1
	goto_if_eq NicknameBoxMon_2
NicknameBoxMon_1:
# 1602 "data/scripts/pkmn_center_nurse.pory"
	setvar VAR_TEMP_TRANSFERRED_SPECIES, SPECIES_MAGIKARP
# 1603 "data/scripts/pkmn_center_nurse.pory"
	bufferspeciesname STR_VAR_2, VAR_TEMP_TRANSFERRED_SPECIES
# 1604 "data/scripts/pkmn_center_nurse.pory"
	call Common_EventScript_TransferredToPC
# 1605 "data/scripts/pkmn_center_nurse.pory"
	hidemoneybox
# 1606 "data/scripts/pkmn_center_nurse.pory"
	goto End
	return

NicknameBoxMon_2:
# 1600 "data/scripts/pkmn_center_nurse.pory"
	call Common_EventScript_NameReceivedBoxMon
	goto NicknameBoxMon_1


End::
# 1610 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1611 "data/scripts/pkmn_center_nurse.pory"
	releaseall
	return


OldaleSecondaryMart_Clerk::
# 1615 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1616 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1617 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1618 "data/scripts/pkmn_center_nurse.pory"
	pokemart OldaleSecondaryMart
# 1619 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1620 "data/scripts/pkmn_center_nurse.pory"
	release
	return


PetalburgSecondaryMart_Clerk::
# 1624 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1625 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1626 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1627 "data/scripts/pkmn_center_nurse.pory"
	pokemart PetalburgSecondaryMart
# 1628 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1629 "data/scripts/pkmn_center_nurse.pory"
	release
	return


RustboroSecondaryMart_Clerk::
# 1633 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1634 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1635 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1636 "data/scripts/pkmn_center_nurse.pory"
	pokemart RustboroSecondaryMart
# 1637 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1638 "data/scripts/pkmn_center_nurse.pory"
	release
	return


SlateportSecondaryMart_Clerk::
# 1642 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1643 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1644 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1645 "data/scripts/pkmn_center_nurse.pory"
	pokemart SlateportSecondaryMart
# 1646 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1647 "data/scripts/pkmn_center_nurse.pory"
	release
	return


MauvilleSecondaryMart_Clerk::
# 1651 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1652 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1653 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1654 "data/scripts/pkmn_center_nurse.pory"
	pokemart MauvilleSecondaryMart
# 1655 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1656 "data/scripts/pkmn_center_nurse.pory"
	release
	return


VerdanturfSecondaryMart_Clerk::
# 1660 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1661 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1662 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1663 "data/scripts/pkmn_center_nurse.pory"
	pokemart VerdanturfSecondaryMart
# 1664 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1665 "data/scripts/pkmn_center_nurse.pory"
	release
	return


FallarborSecondaryMart_Clerk::
# 1669 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1670 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1671 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1672 "data/scripts/pkmn_center_nurse.pory"
	pokemart FallarborSecondaryMart
# 1673 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1674 "data/scripts/pkmn_center_nurse.pory"
	release
	return


LavaridgeSecondaryMart_Clerk::
# 1678 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1679 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1680 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1681 "data/scripts/pkmn_center_nurse.pory"
	pokemart LavaridgeSecondaryMart
# 1682 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1683 "data/scripts/pkmn_center_nurse.pory"
	release
	return


FortreeSecondaryMart_Clerk::
# 1687 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1688 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1689 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1690 "data/scripts/pkmn_center_nurse.pory"
	pokemart FortreeSecondaryMart
# 1691 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1692 "data/scripts/pkmn_center_nurse.pory"
	release
	return


MossdeepSecondaryMart_Clerk::
# 1696 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1697 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1698 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1699 "data/scripts/pkmn_center_nurse.pory"
	pokemart MossdeepSecondaryMart
# 1700 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1701 "data/scripts/pkmn_center_nurse.pory"
	release
	return


SootopolisSecondaryMart_Clerk::
# 1705 "data/scripts/pkmn_center_nurse.pory"
	lock
# 1706 "data/scripts/pkmn_center_nurse.pory"
	message gText_HowMayIServeYou
# 1707 "data/scripts/pkmn_center_nurse.pory"
	waitmessage
# 1708 "data/scripts/pkmn_center_nurse.pory"
	pokemart SootopolisSecondaryMart
# 1709 "data/scripts/pkmn_center_nurse.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 1710 "data/scripts/pkmn_center_nurse.pory"
	release
	return


EventScript_NatureMintNPC_Text_0:
# 265 "data/scripts/pkmn_center_nurse.pory"
	.string "Would you like to make a Nature Mint\n"
	.string "with a Blank Nature Mint?$"

EventScript_NatureMintNPC_Text_1:
# 272 "data/scripts/pkmn_center_nurse.pory"
	.string "You do not have any Blank Nature Mints.$"

EventScript_NatureMintNPC_Text_2:
# 275 "data/scripts/pkmn_center_nurse.pory"
	.string "Which stat would you like the mint to\n"
	.string "increase?$"

EventScript_NatureMintNPC_Text_3:
# 295 "data/scripts/pkmn_center_nurse.pory"
	.string "Which stat would you like the mint to\n"
	.string "decrease?$"

EventScript_NatureMintNPC_Text_4:
# 320 "data/scripts/pkmn_center_nurse.pory"
	.string "Are you sure you want to make a Neutral\n"
	.string "Nature Mint?$"

EventScript_NatureMintNPC_Text_5:
# 331 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Lonely Nature\n"
	.string "Mint (+Atk -Def)?$"

EventScript_NatureMintNPC_Text_6:
# 339 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make an Adamant\n"
	.string "Nature Mint (+Atk -SpA)?$"

EventScript_NatureMintNPC_Text_7:
# 347 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Naughty Nature\n"
	.string "Mint (+Atk -SpD)?$"

EventScript_NatureMintNPC_Text_8:
# 355 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Brave Nature\n"
	.string "Mint (+Atk -Spe)?$"

EventScript_NatureMintNPC_Text_9:
# 368 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Bold Nature\n"
	.string "Mint (+Def -Atk)?$"

EventScript_NatureMintNPC_Text_10:
# 376 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make an Impish Nature\n"
	.string "Mint (+Def -SpA)?$"

EventScript_NatureMintNPC_Text_11:
# 384 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Lax Nature Mint\n"
	.string "(+Def -SpD)?$"

EventScript_NatureMintNPC_Text_12:
# 392 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Relaxed Nature\n"
	.string "Mint (+Def -Spe)?$"

EventScript_NatureMintNPC_Text_13:
# 405 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Modest Nature\n"
	.string "Mint (+SpA -Atk)?$"

EventScript_NatureMintNPC_Text_14:
# 413 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Mild Nature\n"
	.string "Mint (+SpA -Def)?$"

EventScript_NatureMintNPC_Text_15:
# 421 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Rash Nature\n"
	.string "Mint (+SpA -SpD)?$"

EventScript_NatureMintNPC_Text_16:
# 429 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Quiet Nature\n"
	.string "Mint (+SpA -Spe)?$"

EventScript_NatureMintNPC_Text_17:
# 442 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Calm Nature\n"
	.string "Mint (+SpD -Atk)?$"

EventScript_NatureMintNPC_Text_18:
# 450 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Gentle Nature\n"
	.string "Mint (+SpD -Def)?$"

EventScript_NatureMintNPC_Text_19:
# 458 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Careful Nature\n"
	.string "Mint (+SpD -SpA)?$"

EventScript_NatureMintNPC_Text_20:
# 466 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Sassy Nature\n"
	.string "Mint (+SpD -Spe)?$"

EventScript_NatureMintNPC_Text_21:
# 479 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Timid Nature\n"
	.string "Mint (+Spe -Atk)?$"

EventScript_NatureMintNPC_Text_22:
# 487 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Hasty Nature\n"
	.string "Mint (+Spe -Def)?$"

EventScript_NatureMintNPC_Text_23:
# 495 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Jolly Nature\n"
	.string "Mint (+Spe -SpA)?$"

EventScript_NatureMintNPC_Text_24:
# 503 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to make a Naive Nature\n"
	.string "Mint (+Spe -SpD)?$"

EventScript_PreDamageNPC_Text_0:
# 519 "data/scripts/pkmn_center_nurse.pory"
	.string "Would you like to Pre-Damage or\n"
	.string "Pre-Status one of your Pokémon?$"

EventScript_PreDamageNPC_Text_1:
# 526 "data/scripts/pkmn_center_nurse.pory"
	.string "A Pokémon Egg cannot be Pre-Damaged.$"

EventScript_PreDamageNPC_Text_2:
# 531 "data/scripts/pkmn_center_nurse.pory"
	.string "A Fainted Pokémon cannot be\n"
	.string "Pre-Damaged.$"

EventScript_PreDamageNPC_Text_3:
# 539 "data/scripts/pkmn_center_nurse.pory"
	.string "Set your {STR_VAR_1}'s HP to\n"
	.string "{STR_VAR_3}.$"

EventScript_PreDamageNPC_Text_4:
# 546 "data/scripts/pkmn_center_nurse.pory"
	.string "A Pokémon Egg cannot be Pre-Statused.$"

EventScript_PreDamageNPC_Text_5:
# 551 "data/scripts/pkmn_center_nurse.pory"
	.string "A Fainted Pokémon cannot be\n"
	.string "Pre-Statused.$"

EventScript_PreDamageNPC_Text_6:
# 554 "data/scripts/pkmn_center_nurse.pory"
	.string "Which Status would you like to give the\n"
	.string "Pokémon?$"

EventScript_PreDamageNPC_Text_7:
# 575 "data/scripts/pkmn_center_nurse.pory"
	.string "Steel-type Pokémon cannot be\n"
	.string "Poisoned.$"

EventScript_PreDamageNPC_Text_8:
# 583 "data/scripts/pkmn_center_nurse.pory"
	.string "Poison-type Pokémon cannot be\n"
	.string "Poisoned.$"

EventScript_PreDamageNPC_Text_9:
# 591 "data/scripts/pkmn_center_nurse.pory"
	.string "Inflicted your {STR_VAR_1} with\n"
	.string "Poison.$"

EventScript_PreDamageNPC_Text_10:
# 595 "data/scripts/pkmn_center_nurse.pory"
	.string "Electric-type Pokémon cannot be\n"
	.string "Paralyzed.$"

EventScript_PreDamageNPC_Text_11:
# 602 "data/scripts/pkmn_center_nurse.pory"
	.string "Inflicted your {STR_VAR_1} with\n"
	.string "Paralysis.$"

EventScript_PreDamageNPC_Text_12:
# 607 "data/scripts/pkmn_center_nurse.pory"
	.string "{STR_VAR_1}'s ability prevents it\n"
	.string "from being put to Sleep.$"

EventScript_PreDamageNPC_Text_13:
# 614 "data/scripts/pkmn_center_nurse.pory"
	.string "Inflicted your {STR_VAR_1} with\n"
	.string "Sleep.$"

EventScript_PreDamageNPC_Text_14:
# 618 "data/scripts/pkmn_center_nurse.pory"
	.string "Fire-type Pokémon cannot be Burned.$"

EventScript_PreDamageNPC_Text_15:
# 625 "data/scripts/pkmn_center_nurse.pory"
	.string "Inflicted your {STR_VAR_1} with\n"
	.string "Burn.$"

EventScript_PreDamageNPC_Text_16:
# 629 "data/scripts/pkmn_center_nurse.pory"
	.string "Ice-type Pokémon cannot be Frozen.$"

EventScript_PreDamageNPC_Text_17:
# 636 "data/scripts/pkmn_center_nurse.pory"
	.string "Inflicted your {STR_VAR_1} with\n"
	.string "Freeze.$"

EventScript_PreDamageNPC_Text_18:
# 642 "data/scripts/pkmn_center_nurse.pory"
	.string "Steel-type Pokémon cannot be Badly\n"
	.string "Poisoned.$"

EventScript_PreDamageNPC_Text_19:
# 650 "data/scripts/pkmn_center_nurse.pory"
	.string "Poison-type Pokémon cannot be Badly\n"
	.string "Poisoned.$"

EventScript_PreDamageNPC_Text_20:
# 658 "data/scripts/pkmn_center_nurse.pory"
	.string "Inflicted your {STR_VAR_1} with\n"
	.string "Toxic Poison.$"

EventScript_HyperTrainNPC_Text_0:
# 668 "data/scripts/pkmn_center_nurse.pory"
	.string "Would you like to Hyper Train one of\n"
	.string "your Pokémon?$"

EventScript_HyperTrainNPC_Text_1:
# 675 "data/scripts/pkmn_center_nurse.pory"
	.string "You do not have any Bottle Caps.$"

EventScript_HyperTrainNPC_Text_2:
# 682 "data/scripts/pkmn_center_nurse.pory"
	.string "A Pokémon Egg cannot be Hyper Trained.$"

EventScript_HyperTrainNPC_Text_3:
# 685 "data/scripts/pkmn_center_nurse.pory"
	.string "Which stat would you like to train?$"

EventScript_HyperTrainNPC_Text_4:
# 720 "data/scripts/pkmn_center_nurse.pory"
	.string "Your {STR_VAR_1}'s {STR_VAR_3}\n"
	.string "is already at it's maximum!$"

EventScript_HyperTrainNPC_Text_5:
# 740 "data/scripts/pkmn_center_nurse.pory"
	.string "Your {STR_VAR_1}'s {STR_VAR_3}\n"
	.string "has been hyper trained.$"

BPShopClerk_Text_0:
# 747 "data/scripts/pkmn_center_nurse.pory"
	.string "I sell certain items in exchange for\n"
	.string "Battle Points.$"

BPShopClerk_Text_1:
# 750 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have any Battle Points. Come\n"
	.string "back with some.$"

BPShopClerk_Text_2:
# 753 "data/scripts/pkmn_center_nurse.pory"
	.string "Would you like to buy anything?$"

TryBuyEviolite_Text_0:
# 800 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy an Eviolite?$"

TryBuyEviolite_Text_1:
# 812 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough Battle Points.$"

TryBuyEviolite_Text_2:
# 817 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have bag space for this item.$"

TryBuyEviolite_Text_3:
# 825 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Eviolite! Thank you very\n"
	.string "much.$"

TryBuyRareCandy_Text_0:
# 830 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy a Rare Candy?$"

TryBuyRareCandy_Text_1:
# 850 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Rare Candy! Thank you very\n"
	.string "much.$"

TryBuyToxicOrb_Text_0:
# 855 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy a Toxic Orb?$"

TryBuyToxicOrb_Text_1:
# 870 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Toxic Orb! Thank you very\n"
	.string "much.$"

TryBuyFlameOrb_Text_0:
# 875 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy a Flame Orb?$"

TryBuyFlameOrb_Text_1:
# 890 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Flame Orb! Thank you very\n"
	.string "much.$"

TryBuyFocusSash_Text_0:
# 895 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy a Focus Sash?$"

TryBuyFocusSash_Text_1:
# 910 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Focus Sash! Thank you very\n"
	.string "much.$"

TryBuyEjectPack_Text_0:
# 915 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy an Eject Pack?$"

TryBuyEjectPack_Text_1:
# 930 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Eject Pack! Thank you very\n"
	.string "much.$"

TryBuyEjectButton_Text_0:
# 935 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy an Eject Button?$"

TryBuyEjectButton_Text_1:
# 955 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Eject Button! Thank you\n"
	.string "very much.$"

TryBuyBlackSludge_Text_0:
# 960 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy a Black Sludge?$"

TryBuyBlackSludge_Text_1:
# 980 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Black Sludge! Thank you\n"
	.string "very much.$"

TryBuyLeftovers_Text_0:
# 985 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy some Leftovers?$"

TryBuyLeftovers_Text_1:
# 1005 "data/scripts/pkmn_center_nurse.pory"
	.string "Here are your Leftovers! Thank you\n"
	.string "very much.$"

TryBuyAssaultVest_Text_0:
# 1010 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy an Assault Vest?$"

TryBuyAssaultVest_Text_1:
# 1030 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Assault Vest! Thank you\n"
	.string "very much.$"

TryBuyAbilityPatch_Text_0:
# 1035 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy an Ability Patch?$"

TryBuyAbilityPatch_Text_1:
# 1055 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Ability Patch! Thank you\n"
	.string "very much.$"

TryBuyLifeOrb_Text_0:
# 1060 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy a Life Orb?$"

TryBuyLifeOrb_Text_1:
# 1080 "data/scripts/pkmn_center_nurse.pory"
	.string "Here is your Life Orb! Thank you very\n"
	.string "much.$"

EggMoveTutor_Text_0:
# 1085 "data/scripts/pkmn_center_nurse.pory"
	.string "I can teach one of your Pokémon one of\n"
	.string "their egg moves in exchange for one\l"
	.string "Battle Point.$"

EggMoveTutor_Text_1:
# 1091 "data/scripts/pkmn_center_nurse.pory"
	.string "Would you like to do that?$"

EggMoveTutor_Text_2:
# 1103 "data/scripts/pkmn_center_nurse.pory"
	.string "I can't teach a move to an Egg.$"

EggMoveTutor_Text_3:
# 1108 "data/scripts/pkmn_center_nurse.pory"
	.string "This Pokémon does not have any egg\n"
	.string "moves.$"

EggMoveTutor_Text_4:
# 1112 "data/scripts/pkmn_center_nurse.pory"
	.string "Which move would you like me to teach\n"
	.string "{STR_VAR_1}?$"

EventScript_FishermanSalesman_Text_0:
# 1123 "data/scripts/pkmn_center_nurse.pory"
	.string "I am the master fisherman. I have\n"
	.string "travelled all throughout Hoenn and\l"
	.string "caught every type of fish there is.$"

EventScript_FishermanSalesman_Text_1:
# 1126 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy any\n"
	.string "fish. Come back later with more money.$"

EventScript_FishermanSalesman_Text_2:
# 1129 "data/scripts/pkmn_center_nurse.pory"
	.string "Would you like to buy one?$"

TryBuyMagikarp_Text_0:
# 1175 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Magikarp for\n"
	.string "¥500?$"

TryBuyMagikarp_Text_1:
# 1186 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Magikarp.$"

TryBuyMagikarp_Text_2:
# 1195 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have any room in your boxes\n"
	.string "for a new Pokémon.$"

TryBuyGoldeen_Text_0:
# 1202 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Goldeen for ¥500?$"

TryBuyGoldeen_Text_1:
# 1213 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Goldeen.$"

TryBuyRemoraid_Text_0:
# 1229 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Remoraid for\n"
	.string "¥500?$"

TryBuyRemoraid_Text_1:
# 1240 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Remoraid.$"

TryBuyFeebas_Text_0:
# 1258 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Feebas. Come back later with more\l"
	.string "money.$"

TryBuyFeebas_Text_1:
# 1262 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Feebas for ¥1000?$"

TryBuyFeebas_Text_2:
# 1273 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Feebas.$"

TryBuyFinneon_Text_0:
# 1291 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Finneon. Come back later with more\l"
	.string "money.$"

TryBuyFinneon_Text_1:
# 1295 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Finneon for\n"
	.string "¥1000?$"

TryBuyFinneon_Text_2:
# 1306 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Finneon.$"

TryBuyTynamo_Text_0:
# 1324 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Tynamo. Come back later with more\l"
	.string "money.$"

TryBuyTynamo_Text_1:
# 1328 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Tynamo for ¥1000?$"

TryBuyTynamo_Text_2:
# 1339 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Tynamo.$"

TryBuyArrokuda_Text_0:
# 1357 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Arrokuda. Come back later with more\l"
	.string "money.$"

TryBuyArrokuda_Text_1:
# 1361 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Arrokuda for\n"
	.string "¥1000?$"

TryBuyArrokuda_Text_2:
# 1372 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Arrokuda.$"

TryBuyBarboach_Text_0:
# 1390 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Barboach. Come back later with more\l"
	.string "money.$"

TryBuyBarboach_Text_1:
# 1394 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Barboach for\n"
	.string "¥1000?$"

TryBuyBarboach_Text_2:
# 1405 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Barboach.$"

TryBuyChinchou_Text_0:
# 1423 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Chinchou. Come back later with more\l"
	.string "money.$"

TryBuyChinchou_Text_1:
# 1427 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Chinchou for\n"
	.string "¥5000?$"

TryBuyChinchou_Text_2:
# 1438 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Chinchou.$"

TryBuyCarvanha_Text_0:
# 1456 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Carvanha. Come back later with more\l"
	.string "money.$"

TryBuyCarvanha_Text_1:
# 1460 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Carvanha for\n"
	.string "¥5000?$"

TryBuyCarvanha_Text_2:
# 1471 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Carvanha.$"

TryBuyQwilfish_Text_0:
# 1489 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Qwilfish. Come back later with more\l"
	.string "money.$"

TryBuyQwilfish_Text_1:
# 1493 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Qwilfish for\n"
	.string "¥10000?$"

TryBuyQwilfish_Text_2:
# 1504 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Qwilfish.$"

TryBuyBasculin_Text_0:
# 1522 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Basculin. Come back later with more\l"
	.string "money.$"

TryBuyBasculin_Text_1:
# 1526 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Basculin for\n"
	.string "¥10000?$"

TryBuyBasculin_Text_2:
# 1537 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Basculin.$"

TryBuyCosmog_Text_0:
# 1555 "data/scripts/pkmn_center_nurse.pory"
	.string "You don't have enough money to buy\n"
	.string "Cosmog. Come back later with more\l"
	.string "money.$"

TryBuyCosmog_Text_1:
# 1559 "data/scripts/pkmn_center_nurse.pory"
	.string "You would like to buy Cosmog for\n"
	.string "¥50000?$"

TryBuyCosmog_Text_2:
# 1570 "data/scripts/pkmn_center_nurse.pory"
	.string "Obtained Cosmog.$"

NicknamePartyMon_Text_0:
# 1586 "data/scripts/pkmn_center_nurse.pory"
	.string "Do you want to give it a nickame?$"
